### PR TITLE
Replace Webpack with Rollup

### LINKED ISSUE #7471: Build broken on Node 22 Windows
Seen in https://github.com/refined-github/refined-github/pull/7470

It looks like webpack can't find the config file on Windows 🤷‍♂️ 

```
> x:webpack
> cross-env NODE_OPTIONS="--import tsx --no-warnings=ExperimentalWarning" webpack --mode=production webpack-stats.json

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.entry[0] should be a non-empty string.
   -> A module that is loaded upon startup. Only the last one is exported.
```

### PR DESCRIPTION
**Pull request by fregante**
- Closes #7471 
- Related to https://github.com/refined-github/refined-github/pull/6609
- Ideally followed up by https://github.com/rollup/rollup/issues/5626

I'm interested in Rollup's ability to spit out independent files instead of a single bundle.

~~This is not done yet, it's having issues with the .d.ts import https://github.com/rollup/plugins/issues/992~~

### CODE REVIEW

**Comment by fregante** [comment]
```
[!] (plugin readme-plugin) Error: Could not load ./refined-github/readme.md (imported by source/options.tsx): Cannot find module './refined-github/readme-parser-bhiWxXuB.js' imported from ./refined-github/rollup.config-1718791086347.mjs
```

🤷‍♂️ 

The typescript converter spits out the wrong path for the generated file, even if the `import()` for the parser is correct. 🤦‍♂️

File: build/readme-parser.js
Comment (fregante) [inline build/readme-parser.js:1]: I got it to build by turning this TS file into JS. Not ideal but not a big loss.

File: rollup.config.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+	output: {
+		dir: 'distribution/assets',
+		// AssetFileNames: "[name]-[hash][extname]", // for CSS
+	},
+	plugins: [
+		json(), // TODO: Drop after https://github.com/refined-github/shorten-repo-url/issues/47
+		styles(),
+		string({
+			include: '**/*.gql',
+		}),
```
Comment (fregante) [inline rollup.config.js:28]: This could use a GQL-specific plugin in the future, but for now it's 1:1 for easier upgrade.

- https://github.com/rollup/plugins/tree/master/packages/graphql
- #6686

File: rollup.config.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+		alias({
+			entries: [
+				{find: 'react', replacement: 'dom-chef'},
+				{find: '@cheap-glitch/mi-cron', replacement: '@cheap-glitch/mi-cron/index.min.js'},
```
Comment (fregante) [inline rollup.config.js:32]: Rollup is picking up the .ts file to read the exported values (ESM) and then using the `main` entry point (CJS) 🤦‍♂️ 🤷‍♂️ 

Could be solved by:

- https://github.com/cheap-glitch/mi-cron/issues/10

File: .github/workflows/test.yml [hunk 3]
```diff
@@ -65,13 +65,6 @@ jobs:
           node-version-file: package.json
           cache: npm
       - run: npm ci
-      - run: npm run build:webpack -- --json webpack-stats.json
-      - name: Send webpack stats to RelativeCI
-        if: matrix.os == 'ubuntu-latest'
-        uses: relative-ci/agent-action@v2
-        with:
-          webpackStatsFile: ./webpack-stats.json
-          key: ${{ secrets.RELATIVE_CI_KEY }}
```
Comment (fregante) [inline .github/workflows/test.yml:74]: Probably:

- https://github.com/relative-ci/rollup-plugin-webpack-stats

**Review by fregante — COMMENTED** [review]
The extension is completely unbundled now 🎉

Screenshot 2

It looks like I'm missing:

- [ ] CSS extraction
- [x] manifest.json copy to dist
- [ ] Restore RelativeCI stats
- [ ] Ensure it still works

**Comment by fregante** [comment]
So close, yet so far.

CSS files are extracted, but `preserveModules: true` _also_ causes CSS files to not be bundled, but we don't want that (rather, it does _not_ preserve `@import`s to these files, which are now orphaned)

**Comment by fregante** [comment]
Wah… have we finally reached this point? It appears to work 😱 

I've been trying to move off of Webpack for years and we've finally come full circle:

- https://github.com/refined-github/refined-github/pull/577

Complexity-wise, the advantages of Rollup over Webpack are minor or non-existent, but we gain the ability to output separate files. This means we will be able to drop hacks like `id: import.meta.url` and `features.log.error(import.meta.url)`. Also any uncaught errors are no longer attached to `refined-github.js` but to the specific file (or feature) where they are thrown.

These improvements can come later, when our new Rollup build has been validated.

**Comment by fregante** [comment]
A couple of warnings:


```

(!) "this" has been rewritten to "undefined"
https://rollupjs.org/troubleshooting/#error-this-is-undefined
node_modules/webext-options-sync-per-domain/index.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                     ^
2:     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key...
3:     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, targe...
...and 1 other occurrence
(!) Circular dependency
source/github-helpers/github-token.ts -> source/github-helpers/api.ts -> source/github-helpers/github-token.ts
```

**Comment by fregante** [comment]
@kidonng @yakov116 does anyone of you run a dev version daily? It would be good to test-drive this version as your daily version.

I didn't see issues but I'm nervous to merge it 😅

**Comment by yakov116** [comment]
I can use it for the next few days

**Comment by fregante** [comment]
SHIPPING TIME
