### PR TITLE
Fix `show-whitespace` on newly sent suggestions

### LINKED ISSUE #2852: `show-whitespace` doesn’t work on newly sent suggestions
Peek 2020-03-03 16-01

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #2852 

## Test URLs

https://togithub.com/refined-github/refined-github/pull/5103/files

## Screenshot

https://user-images.githubusercontent.com/46634000/142915220-243a89cb-9f40-411b-a5da-59119c3287ef.mp4

### CODE REVIEW

File: source/github-events/on-new-review.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+function callbackWrapper(callback: VoidFunction): (event: CustomEvent) => void {
+	return function (event) {
+		if (/^pull request #\d+ updated$/.test(event.detail.data.reason)) {
+			callback();
+		}
+	};
+}
+
+export default function onNewReviewComment(callback: VoidFunction): void {
+	delegate(document, '.js-pull-refresh-on-pjax', 'socket:message', callbackWrapper(callback), {capture: true});
```
Comment (cheap-glitch) [inline source/github-events/on-new-review.ts:12]: This triggers on other events besides new reviews, e.g. when editing or deleting reviews.

In the first case it's actually a good thing I guess, because the contents of the embedded snippets might have been changed and/or added.

File: source/github-events/on-new-review.ts [hunk 2]
```diff
@@ -0,0 +1,13 @@
+import delegate from 'delegate-it';
+
+function callbackWrapper(callback: VoidFunction): (event: CustomEvent) => void {
+	return function (event) {
+		if (/^pull request #\d+ updated$/.test(event.detail.data.reason)) {
```
Comment (cheap-glitch) [inline source/github-events/on-new-review.ts:5]: Not sure if the test is really needed, it seems all the messages are the same (with just the id changing).

**Review by cheap-glitch — COMMENTED** [review]
Attempt at implementing a listener for new review comments.

File: source/github-events/on-new-review.ts [hunk 3]
```diff
@@ -0,0 +1,13 @@
+import delegate from 'delegate-it';
+
+function callbackWrapper(callback: VoidFunction): (event: CustomEvent) => void {
```
Comment (fregante) [inline source/github-events/on-new-review.ts:3]: If you don't memoize this call, then `delegate` will add a new listener every time `onNewReviewComment` is called. Event listeners are natively deduplicated if the same exact function is passed to it. Something like:
```suggestion
const callbackWrapper = mem((callback: VoidFunction): (event: CustomEvent) => void => {
```

File: source/github-events/on-new-review.ts (hunk 1 above)
Comment (fregante) [reply source/github-events/on-new-review.ts:12]: `socket:message` can't be used I think. The message doesn't always equal DOM change, which sometimes happens later. We had this issue a few years ago when implementing `onNewComments`, not sure if it applies here.

If it works… it's fine for now.

File: source/github-events/on-new-review.ts (hunk 2 above)
Comment (fregante) [reply source/github-events/on-new-review.ts:5]: The issue is that this event might also be dispatched when a regular comment comes in, so it would effectively duplicate `onNewComment` as well.

Comment (cheap-glitch) [reply source/github-events/on-new-review.ts:5]: > The issue is that this event might also be dispatched when a regular comment comes in

It is, but not from the same source, so the delegation ignores it.

The issue is that it is dispatched three times when sending a quick review (with "Add single review comment" button), and afaict the three events are virtually indistinguishable :grimacing:

Comment (fregante) [reply source/github-events/on-new-review.ts]: That doesn't sound right. What's happening though is that we have a simple loop with deduplication in `init`. So even if it's called twice, no duplication happens.

It may be ok, but I'm still wary of this event and I'd probably merge it back into this file so we know it's not safe for general use. A comment like this should also be inlined.

**Review by fregante — APPROVED** [review]

**Comment by kidonng** [comment]
Thanks for solving an oldest bug 🔥
