### PR TITLE
Fix implementation of hotfixes

### LINKED ISSUE #4861: The hotfix expires too soon
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

GitHub feed showing weird white-colored panel in the middle. I'm using Brave browser with dark mode enabled.

### Screenshot

Without extension (default): 

image

With extension: 

image

### Console errors

_No response_

### Example URL

https://github.com/

### Browser(s) used

Brave (Chromium-based)

### PR DESCRIPTION
**Pull request by cheap-glitch**
Follow-up of https://github.com/refined-github/refined-github/pull/4961#pullrequestreview-796250499
Fixes #4861 

## Test URLs
n/a

## Screenshot
screenshot-1636376145

### CODE REVIEW

File: source/helpers/hotfix.ts [hunk 1]
```diff
@@ -15,10 +17,16 @@ export const updateHotfixes = cache.function(async (): Promise<string[][]> => {
...
 	}
 
-	return atob(content)
-		.trim()
-		.split('\n')
-		.map(line => line.split(','));
+	const storage: HotfixStorage = [];
+	const lines = atob(content).trim().split('\n');
+	for (const line of lines) {
+		const [featureID, unaffectedVersion, relatedIssue] = line.split(',');
```
Comment (cheap-glitch) [inline source/helpers/hotfix.ts:23]: Maybe the line itself should be trimmed too just in case?

File: source/helpers/hotfix.ts [hunk 2]
```diff
@@ -15,10 +17,16 @@ export const updateHotfixes = cache.function(async (): Promise<string[][]> => {
...
+		if (!unaffectedVersion || compareVersions(unaffectedVersion, version) > 0) {
```
Comment (cheap-glitch) [inline source/helpers/hotfix.ts:24]: We could also check that `featureID` and `relatedIssue` are not empty of `undefined` (that would avoid storing the example line).

File: source/features/index.tsx [hunk 3]
```diff
@@ -109,7 +109,7 @@ const globalReady: Promise<RGHOptions> = new Promise(async resolve => {
 		Object.assign(options, bisectedFeatures);
 	} else {
 		// If features are remotely marked as "seriously breaking" by the maintainers, disable them without having to wait for proper updates to propagate #3529
-		void updateHotfixes();
+		void updateHotfixes(version);
```
Comment (fregante) [inline source/features/index.tsx:112]: ?



The cache is already updated when the version changes, there's only ever one cache per version. This applies to both JS and CSS fixes

File: source/helpers/hotfix.ts (hunk 1 above)
Comment (fregante) [reply source/helpers/hotfix.ts:23]: Maybe
```suggestion
		const [featureID, unaffectedVersion, relatedIssue] = line.split(/\s*,\s*/);
```

**Review by fregante — COMMENTED** [review]
<3

File: source/features/index.tsx (hunk 3 above)
Comment (cheap-glitch) [reply source/features/index.tsx:112]: We need it to compare to the unaffected versions when filtering. Also for `updateStyleHotfixes()` it's used to construct the file URL.

Though I guess it could be grabbed directly in `hotfix.ts`.

**Comment by fregante** [comment]
Related, if you want to look into it https://github.com/refined-github/refined-github/issues/4861

File: source/helpers/hotfix.ts [hunk 4]
```diff
@@ -15,12 +28,17 @@ export const updateHotfixes = cache.function(async (): Promise<string[][]> => {
...
+	for (const [featureID, unaffectedVersion, relatedIssue] of parseCsv(atob(content))) {
+		if (featureID && relatedIssue && (!unaffectedVersion || compareVersions(unaffectedVersion, version) > 0)) {
+			storage.push([featureID as FeatureID, relatedIssue]);
+		}
+	}
+
+	return storage;
 }, {
 	maxAge: {hours: 6},
+	staleWhileRevalidate: {days: 3},
```
Comment (cheap-glitch) [inline source/helpers/hotfix.ts:41]: Hopefully this fixes the situation described in https://github.com/refined-github/refined-github/issues/4861#issuecomment-933148944.

Comment (cheap-glitch) [reply source/helpers/hotfix.ts:41]: @fregante :rocket: ?

File: source/helpers/hotfix.ts [hunk 5]
```diff
@@ -15,12 +28,17 @@ export const updateHotfixes = cache.function(async (): Promise<string[][]> => {
...
 	}
 
-	return atob(content)
-		.trim()
-		.split('\n')
-		.map(line => line.split(','));
+	const storage: HotfixStorage = [];
+	for (const [featureID, unaffectedVersion, relatedIssue] of parseCsv(atob(content))) {
+		if (featureID && relatedIssue && (!unaffectedVersion || compareVersions(unaffectedVersion, version) > 0)) {
+			storage.push([featureID as FeatureID, relatedIssue]);
```
Comment (fregante) [inline source/helpers/hotfix.ts:34]: Is this not working? All of them are still appearing locally even if I have v21.11.1. Safari

Screen Shot 5
