### PR TITLE
Restore `rgh-improve-new-issue-form`

### LINKED ISSUE #6300: The issue reporter logger generates an outdated link
### Description

This piece of code

https://github.com/refined-github/refined-github/blob/7b2e3e5178f366dd543525f392338b16fac4ac61/source/feature-manager.tsx#L75-L80

Generated:

> https://github.com/refined-github/refined-github/issues/new?labels=bug&template=1_bug_report.yml&title=%60list-prs-for-file%60%3A+Cannot+read+properties+of+undefined+%28reading+%27getAttribute%27%29&example_urls=https%3A%2F%2Fgithub.com%2Frefined-github%2Fyolo%2Fblob%2Fmain%2Fbroken-features.csv&description=%60%60%60%0ATypeError%3A+Cannot+read+properties+of+undefined+%28reading+%27getAttribute%27%29%0A++++at+getCurrentPath+%28chrome-extension%3A%2F%2Fjfnbjdajagmjideggedlljgaddlmffhd%2Frefined-github.js%3A9747%3A18%29%0A++++at+async+Promise.all+%28index+0%29%0A++++at+async+init+%28chrome-extension%3A%2F%2Fjfnbjdajagmjideggedlljgaddlmffhd%2Frefined-github.js%3A9750%3A29%29%0A++++at+async+runFeature+%28chrome-extension%3A%2F%2Fjfnbjdajagmjideggedlljgaddlmffhd%2Frefined-github.js%3A3797%3A16%29%0A++++at+async+setupPageLoad+%28chrome-extension%3A%2F%2Fjfnbjdajagmjideggedlljgaddlmffhd%2Frefined-github.js%3A3809%3A5%29%0A%60%60%60

But that doesn't fill in any data in the form, probably because we changed the template to make it more specific.

Are URL parameters still supported? If they are, we should:

- [ ] Update the code above
- [ ] Add comments in the issue templates and in the code so we're reminded that these two pieces are linked together

### How to replicate the issue + URL

Follow the repro steps in https://github.com/refined-github/refined-github/issues/6299 while it's still broken

### Extension version

23.2.1

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by fregante**
- Includes https://github.com/refined-github/refined-github/issues/5222#issuecomment-1070341541
- Fixes #6300

## Test URLs

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml

## Screenshot

More exact notice:

Screenshot

Screenshot 1

### CODE REVIEW

File: source/features/rgh-improve-new-issue-form.tsx [hunk 1]
```diff
@@ -5,12 +5,42 @@ import * as pageDetect from 'github-url-detection';
...
+		addNotice('invalid or expired');
+	}
+}
+
+async function setVersion(): Promise<void> {
 	const {version} = browser.runtime.getManifest();
-	select('input#issue_form_extension_version')!.value = version;
+	const versionFieldId = 'issue_form_4ceb28848d92a2c2094093043f57e5e4cb152518a3c2b3b950d1273f795dc13c';
+	assertNodeContent(select(`label[for="${versionFieldId}"`)!.firstChild, 'Extension version');
+	select(`input#${versionFieldId}`)!.value = version;
```
Comment (fregante) [inline source/features/rgh-improve-new-issue-form.tsx:40]: Dynamic IDs. Hopefully they're actually hashes of user content rather than totally random.

This was breaking each part of the feature, so I refactored it to avoid this issue in the future

File: source/features/rgh-improve-new-issue-form.tsx [hunk 2]
```diff
@@ -5,12 +5,42 @@ import * as pageDetect from 'github-url-detection';
...
+		await expectToken();
+	} catch {
+		addNotice('missing');
+		return;
+	}
+
+	try {
+		await expectTokenScope('repo');
+	} catch {
+		addNotice('invalid or expired');
```
Comment (fregante) [inline source/features/rgh-improve-new-issue-form.tsx:32]: The API just returns `Bad credentials` so we can't know further details, I think.

File: source/features/rgh-improve-new-issue-form.tsx [hunk 3]
```diff
@@ -20,14 +50,15 @@ function init(): void {
...
-			<div className="flash flash-warn m-2">
-				Your Personal Access Token is either missing, incorrect or expired. Some Refined GitHub features will not work without it.<br/>
-				You can update it <a href="#" onClick={openOptions as unknown as React.MouseEventHandler}>in the options</a>.
-			</div>,
-		);
-	});
+}
+
+async function init(): Promise<void> {
+// Asyn functions so they're independent
```
Comment (FloEdelmann) [inline source/features/rgh-improve-new-issue-form.tsx:56]:
```suggestion
	// Async functions so they're independent
```

Comment (fregante) [reply source/features/rgh-improve-new-issue-form.tsx]: thank you!

File: source/feature-manager.tsx [hunk 4]
```diff
@@ -76,7 +76,7 @@ const logError = (url: string, error: unknown): void => {
 	newIssueUrl.searchParams.set('labels', 'bug');
 	newIssueUrl.searchParams.set('template', '1_bug_report.yml');
 	newIssueUrl.searchParams.set('title', `\`${id}\`: ${message}`);
-	newIssueUrl.searchParams.set('example_urls', location.href);
+	newIssueUrl.searchParams.set('repro', location.href);
 	newIssueUrl.searchParams.set('description', [
```
Comment (fregante) [inline source/feature-manager.tsx:80]: #6300 should work now thanks to aed513d. I'm including it here because they're related

File: source/features/rgh-improve-new-issue-form.tsx (hunk 1 above)
Comment (fregante) [reply source/features/rgh-improve-new-issue-form.tsx]: Fixed in aed513d
