### PR TITLE
`small-user-avatars` - Fix misalignment 

### LINKED ISSUE #7509: `small-user-avatars` causes misalignment
### Description

`small-user-avatars` disabled:

Screenshot 2024-06-30 at 1 28 13 PM

`small-user-avatars` enabled:

Screenshot 2024-06-30 at 1 28 02 PM

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

### Extension version

24.6.21

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by gxr404**
Closes #7509

## Test URLs

https://github.com/refined-github/refined-github/issues

## Screenshot

small-user-avatars disabled:
|Before|After|
|---|---|
| SCR-20240701-rctj |SCR-20240701-rcwp |

small-user-avatars enabled:

|Before|After|
|---|---|
| SCR-20240701-rcjn |SCR-20240701-rcct |

### CODE REVIEW

File: source/features/small-user-avatars.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ function addAvatar(link: HTMLElement): void {
 	const username = link.textContent;
 	const size = 14;
 
-	link.classList.add('d-inline-block');
+	link.classList.add('d-inline-block', 'rgh-lh-initial');
```
Comment (fregante) [inline source/features/small-user-avatars.tsx:14]: GitHub already has some classes:

```css
.lh-condensed-ultra {
    line-height:1 !important
}

.lh-condensed {
    line-height:1.25 !important
}

.lh-default {
    line-height:1.5 !important
}

.lh-0 {
    line-height:0 !important
}
```

**Review by fregante — CHANGES_REQUESTED** [review]

**Comment by fregante** [comment]
Thank you for the PR!

File: source/features/small-user-avatars.tsx (hunk 1 above)
Comment (gxr404) [reply source/features/small-user-avatars.tsx]: Changed to `lh-condensed-ultra`,  effect is the same
