### PR TITLE
Meta: Improve DX when features are not yet finalized

### LINKED ISSUE #6606: Creating feature for the first time
I'm trying to make a feature that highlights `// TODO` comments and I really can't get it to run :(
The code inside `init()` is not running (the console.log is not printed) and I have this warning in console
> `DevTools failed to load source map: Could not load content for chrome-extension://dehmkhkfkicaaafgjnhpmlocdafjedmh/index.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`
  
Here's the code: https://github.com/iGabyTM/refined-github/tree/feature/highlight-todo-comments

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #6606

### CODE REVIEW

File: source/feature-manager.tsx [hunk 1]
```diff
@@ -227,8 +227,10 @@ const add = async (url: string, ...loaders: FeatureLoader[]): Promise<void> => {
 	const id = getFeatureID(url);
 	/* Feature filtering and running */
 	const options = await globalReady;
-	// Skip disabled features, unless the "feature" is the fake feature in this file
-	if (!options[`feature:${id}`] && !id.startsWith('rgh')) {
+	// Skip disabled features, unless the feature is private
+	// Must check if it's specifically `false`: It could be undefined if not yet in the readme or if misread from the entry point #6606
+	// eslint-disable-next-line @typescript-eslint/no-unnecessary-boolean-literal-compare
+	if (options[`feature:${id}`] === false && !id.startsWith('rgh')) {
```
Comment (fregante) [inline source/feature-manager.tsx:233]: Of course, the second after I merged I realized that the second condition is no longer necessary 😅 

This won't happen anyway:

- https://github.com/refined-github/refined-github/issues/5828
