### PR TITLE
Fix `follow-file-renames` feature

### LINKED ISSUE #5576: `follow-file-renames` directs to 404 due to improper ref in URL
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/app-service/tutorial-connect-msi-sql-database.md

### Extension version

22.4.1

### Browser(s) used

Firefox 99, Chrome 100

### Description

The "Older" button directs to the old name of the file, but keeps the ref in the URL as the branch name, rather than switching to the commit hash. Since the old name no longer exists in the branch, the page is a 404.

Expected: "Older" goes to either https://github.com/MicrosoftDocs/azure-docs/commits/ac26f2e50ad4faea4c0240941eb93dbedfd4e9ec/articles/app-service/tutorial-connect-msi-sqldatabase.md (the last commit on the page) or https://github.com/MicrosoftDocs/azure-docs/commits/8169d11444bcfe3cbf5aa9027a4dbbfada66f60a/articles/app-service/tutorial-connect-msi-sqldatabase.md (the parent commit of the last commit on the page).

Actual: "Older" goes to https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/app-service/tutorial-connect-msi-sqldatabase.md, a 404 (the rename was the addition of a `-` in `sql-database`).

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5576 

## Test URLs

- [Renamed file on main branch](https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/app-service/tutorial-connect-msi-sql-database.md)
- [Renamed file on branch with slashes](https://togithub.com/refined-github/sandbox/commits/branch/with/slashes/renamed.md)

## Screenshot

https://user-images.githubusercontent.com/46634000/162250772-726ab1ec-7653-41bc-8dd5-4bd08c2bea97.mp4

### CODE REVIEW

File: source/features/follow-file-renames.tsx [hunk 1]
```diff
@@ -91,3 +96,10 @@ void features.add(import.meta.url, {
 	],
 	init,
 });
+
+/* Test URLs
+
+- Renamed file on main branch: https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/app-service/tutorial-connect-msi-sql-database.md
+- Renamed file on branch with slashes: https://togithub.com/refined-github/sandbox/commits/branch/with/slashes/renamed.md
+
+*/
```
Comment (fregante) [inline source/features/follow-file-renames.tsx:105]: Maybe
```suggestion
/*
Test URLs:

- Renamed file on main branch: https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/app-service/tutorial-connect-msi-sql-database.md
- Renamed file on branch with slashes: https://togithub.com/refined-github/sandbox/commits/branch/with/slashes/renamed.md
*/
```

File: source/features/follow-file-renames.tsx [hunk 2]
```diff
@@ -57,6 +58,10 @@ async function linkify(button: HTMLButtonElement, filePath: string): Promise<voi
 		// Clear the search from the url, so it does not get passed to the rename link
 		search: '',
 	});
+	if (isOlder) {
+		linkifiedURL.branch = fileChanges.commit.parentSha; // #5576
```
Comment (fregante) [inline source/features/follow-file-renames.tsx:62]: How come this became necessary? The feature worked before

**Review by fregante — APPROVED** [review]

File: source/features/follow-file-renames.tsx (hunk 2 above)
Comment (cheap-glitch) [reply source/features/follow-file-renames.tsx:62]: I was wondering about that too, but I very rarely use this feature so I don't know. Maybe GitHub used to redirect to the last commit where the file existed, but stopped doing it for whatever reason?

Comment (fregante) [reply source/features/follow-file-renames.tsx:62]: hmm that's it, if I remember correctly you could use the commits page on any file and it would just show the commits whether the file existed or not, which would explain why this worked.

**Comment by fregante** [comment]
Unless you have any more quick fixes coming today, please release a new version after merging this PR

**Comment by cheap-glitch** [comment]
> Unless you have any more quick fixes coming today, please release a new version after merging this PR

@fregante Let's merge #5589 (and maybe #5588 too) and ship :ship: :package:
