### PR TITLE
Fix: `conversation-activity-filter` doesn't reset its state when navigating

### LINKED ISSUE #4997: `conversation-activity-filter` doesn't reset its state when opening another page
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

https://user-images.githubusercontent.com/44045911/139123222-aae0d26b-e680-4955-b989-c169d7f90581.mov

Steps to reproduce:

1. Activate `conversation-activity-filter`
2. Navigate to another discussion
3. Notice it stays "enabled" despite the effect no longer take place

### Example URL

Here

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4997 

## Test URLs

https://togithub.com/refined-github/refined-github/issues/4997

## Screenshot

https://user-images.githubusercontent.com/46634000/141775695-a611f3e4-bbf7-493a-b805-56f787db7fdd.mp4

### CODE REVIEW

File: source/features/conversation-activity-filter.tsx [hunk 1]
```diff
@@ -152,6 +152,10 @@ async function addWidget(header: string): Promise<void> {
 }
 
 async function init(): Promise<void> {
+	// Reset the dropdown state #4997
+	currentSetting = 'default';
+	select('.repository-content')!.classList.remove('rgh-conversation-activity-is-filtered');
```
Comment (cheap-glitch) [inline source/features/conversation-activity-filter.tsx:157]: Alternatively this could be a `deinit` function

Comment (yakov116) [reply source/features/conversation-activity-filter.tsx:157]: Which way is safer?

Comment (cheap-glitch) [reply source/features/conversation-activity-filter.tsx:157]: This one I guess? Since it's inside the `init`, it's guaranteed to run before the widgets are created. Since `deinit` is essentially a callback, it *could* fail to run for whatever reason.
