### PR TITLE
`align-issue-labels` -  Support new issue lists

### LINKED ISSUE #8256: `align-issue-labels`: alignment doesn't work for "Issue"
### Description

In issue/PR lists, doesn't aligns the labels to the left, below each title.

Image

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

### Extension version

25.1.24

### Browser(s) used

firefox, zen

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
closes #8256

see the issue for more info

## Test URLs

https://github.com/nrwl/nx/issues

## Screenshot

image

### CODE REVIEW

File: source/features/align-issue-labels.tsx [hunk 1]
```diff
@@ -1,8 +1,56 @@
...
+			continue;
+		}
+
+		issueTypeTokenContainer.classList.add('rgh-issue-type');
+		badgesContainer.prepend(issueTypeTokenContainer);
+	}
+}
+
+async function init(signal: AbortSignal): Promise<void> {
+	observe(issueRowSelector, batchedFunction(alignBadges, {delay: 100}), {signal});
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: batchedFunction is just for API calls. Here "observe" should call `alignBadge` directly

File: source/features/align-issue-labels.tsx [hunk 2]
```diff
@@ -1,8 +1,56 @@
...
+
+const issueRowSelector = '[class^="IssueRow-module__row"]';
+const badgesContainerSelector = '[class*="trailingBadgesContainer"]';
+const mainContentInnerSelector = '[class^="MainContent-module__inner"]';
+const descriptionContainerSelector = '[class^="Description-module__container"]';
+const issueTypeContainerSelector = '[class*="issueTypeTokenContainer"]';
+
+function alignBadges(issueRows: HTMLElement[]): void {
+	for (const issueRow of issueRows) {
+		const badgesContainer = issueRow.querySelector(badgesContainerSelector);
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: Consider shortening variable names to just "badges", "description", "types"

File: source/features/align-issue-labels.tsx [hunk 3]
```diff
@@ -1,8 +1,56 @@
...
+		if (!badgesContainer) {
+			continue;
+		}
+
+		const mainContentInner = issueRow.querySelector(mainContentInnerSelector);
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: All querySelector usage should be replaced with select-dom. Import the "strict" version and then use `$()`

`$optional()` can also be used if it *already* an element doesn't exist. If some must exist now but doesn't in the future, `$()` throws an error so we know when/where the feature failed.

File: source/features/align-issue-labels.css [hunk 4]
```diff
@@ -1,36 +1,22 @@
-html:not([rgh-OFF-align-issue-labels]) .js-issue-row {
```
Comment (fregante) [inline source/features/align-issue-labels.css:1]: The old view is still used on PRs so most likely we need to preserve the old CSS too. 

You can keep the `addCssFeature` call in JS alongside the regular `add`

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css:1]: check failed

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css:1]: could you please show where the old css still works?

Comment (fregante) [reply source/features/align-issue-labels.css:1]: https://github.com/refined-github/refined-github/pulls

Comment (fregante) [reply source/features/align-issue-labels.css:1]: You can delete these lines, they're no longer applicable:

https://github.com/refined-github/refined-github/blob/037fa9a507b83d1cf94a71c318d777551c9ca9df/build/features.test.ts#L165-L168

File: source/features/align-issue-labels.css [hunk 5]
```diff
@@ -34,3 +34,28 @@ html:not([rgh-OFF-align-issue-labels]) .js-issue-row {
 		font-size: 11px !important;
 	}
 }
+
+/* New view */
```
Comment (fregante) [inline source/features/align-issue-labels.css]:
```suggestion
/* React issue lists */
/* TODO: Remove the old styles in 2026 */
```

File: source/features/align-issue-labels.tsx [hunk 6]
```diff
@@ -1,9 +1,54 @@
 import './align-issue-labels.css';
 
+import * as pageDetect from 'github-url-detection';
+import {$, $optional} from 'select-dom/strict.js';
+
 import features from '../feature-manager.js';
+import observe from '../helpers/selector-observer.js';
 
 void features.addCssFeature(import.meta.url);
```
Comment (fregante) [inline source/features/align-issue-labels.tsx:10]:
```suggestion
// TODO: Drop in 2026
void features.addCssFeature(import.meta.url);
```

File: source/features/align-issue-labels.tsx [hunk 7]
```diff
@@ -1,9 +1,54 @@
...
+	mainContent.classList.add('rgh-issue-main-content-inner');
+	mainContent.append(badges);
+
+	if (issueType) {
+		issueType.classList.add('rgh-issue-type');
+		badges.prepend(issueType);
+	}
+
+	const description = $(descriptionSelector, issue);
+	description.classList.add('rgh-issue-description');
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: If the selectors are used only once, it's preferable to have them inline

```suggestion
	$('[class^="Description-module__container"]', issue).classList.add('rgh-issue-description');
```

File: source/features/align-issue-labels.tsx [hunk 8]
```diff
@@ -1,9 +1,54 @@
...
 
+/* New view */
+
+const issueSelector = '[class^="IssueRow-module__row"]';
+const badgesSelector = '[class*="trailingBadgesContainer"]';
+const mainContentSelector = '[class^="MainContent-module__inner"]';
+const descriptionSelector = '[class^="Description-module__container"]';
+const issueTypeSelector = '[class*="issueTypeTokenContainer"]';
+
+function alignBadges(issue: HTMLElement): void {
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]:
```suggestion
function alignBadge(issue: HTMLElement): void {
```

File: source/features/align-issue-labels.tsx [hunk 9]
```diff
@@ -12,5 +57,6 @@ https://github.com/pulls
 https://github.com/bmish/eslint-doc-generator/pulls
 https://github.com/bmish/eslint-doc-generator/issues
 https://github.com/bmish/eslint-doc-generator/milestone/1
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: I'm just replacing the URL.

```suggestion
https://github.com/bmish/eslint-doc-generator/milestone/1?closed=1
```

I assume the feature is broken there, I wouldn't worry about it in this PR.

File: source/features/align-issue-labels.tsx [hunk 10]
```diff
@@ -1,9 +1,54 @@
...
+const mainContentSelector = '[class^="MainContent-module__inner"]';
+const descriptionSelector = '[class^="Description-module__container"]';
+const issueTypeSelector = '[class*="issueTypeTokenContainer"]';
+
+function alignBadges(issue: HTMLElement): void {
+	const badges = $(badgesSelector, issue);
+	const mainContent = $(mainContentSelector, issue);
+	const issueType = $optional(issueTypeSelector, issue);
+
+	if (badges.children.length === 0 && !issueType) {
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: If there are no labels, we shouldn't move anything at all, right?


```suggestion
	if (badges.children.length === 0) {
```

**Review by fregante — COMMENTED** [review]
A few nits 🙏

File: source/features/align-issue-labels.tsx (hunk 10 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.tsx]: I did that so the layout would be consistent

| current | suggested |
|--------|--------|
| image | image |

Comment (fregante) [reply source/features/align-issue-labels.tsx]: I like consistency, but I prefer the "suggested" version for now since it's more compact and avoids DOM changes

File: source/features/align-issue-labels.tsx (hunk 9 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.tsx]: it does work 

image

File: source/features/align-issue-labels.tsx (hunk 8 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.tsx]: but there could be multiple badges and the function aligns them all 🤔

Comment (fregante) [reply source/features/align-issue-labels.tsx]: Oh yeah 😅

File: source/features/align-issue-labels.css [hunk 11]
```diff
@@ -34,3 +34,29 @@ html:not([rgh-OFF-align-issue-labels]) .js-issue-row {
...
+	margin-top: var(--base-size-4);
+}
+
+.rgh-issue-main-content-inner {
+	gap: var(--base-size-4);
+}
+
+.rgh-issue-description {
+	gap: unset;
+}
```
Comment (fregante) [inline source/features/align-issue-labels.css]: Instead of creating custom classes, I think these already exist as utility classes. Maybe they're `mt-1`, `gap-1` and `gap-0`. You'd have to find them in the developer tools, there are CSS files loaded by GitHub named "primer", etc

File: source/features/align-issue-labels.css [hunk 12]
```diff
@@ -34,3 +34,29 @@ html:not([rgh-OFF-align-issue-labels]) .js-issue-row {
...
+
+.rgh-issue-type {
+	display: inline-block;
+	margin-right: var(--base-size-4);
+
+	.rgh-issue-badges:has(:nth-child(2)) &:after {
+		content: '•';
```
Comment (fregante) [inline source/features/align-issue-labels.css]: Not necessary, but if you can copy the line as it's in the app. Here's the light version so you can find the color that works for both light and night mode

Image

**Review by fregante — APPROVED** [review]
🎈

File: source/features/align-issue-labels.css (hunk 12 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: which is better?

| 1 | 2 |
|--------|--------|
| image | image |

File: source/features/align-issue-labels.css (hunk 11 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: there is no utility classes for setting `gap` and we still have to create custom classes for badges and issue type to add a separator

File: source/features/align-issue-labels.css (hunk 12 above)
Comment (fregante) [reply source/features/align-issue-labels.css]: 1

File: source/features/align-issue-labels.tsx [hunk 13]
```diff
@@ -24,15 +24,15 @@ function alignBadges(issue: HTMLElement): void {
 		return;
 	}
 
-	badges.classList.add('rgh-issue-badges');
+	badges.classList.add('rgh-issue-badges', 'mt-1');
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: rgh-issue-badges and rgh-issue-type don't exist anymore, they can be dropped

Comment (SunsetTechuila) [reply source/features/align-issue-labels.tsx]: they do: https://github.com/refined-github/refined-github/commit/a172704293489de5afc48bb87e6a831edc25e4ae#diff-57cfe7f2460a24b5830d888bebaced23a00239bacd74fa83ff654e0e4b27b365R49

File: source/features/align-issue-labels.css (hunk 12 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: I will use the color from the second screenshot because the color in the first is barely visible on the dark theme

**Comment by fregante** [comment]
Thank you it's great! I'll test it out later today and merge it tomorrow.

**Comment by fregante** [comment]
It seems that some aren't covered here:

https://github.com/issues?q=wonderful%20facebook%20space%20bug%20tweet%20downloads%20the%20github%20optional

Screenshot 2

This seems to be ok:

https://github.com/pulls?q=%22refined+github%22+is%3Apr+-repo%3Arefined-github+sweet+bug

**Comment by SunsetTechuila** [comment]
fixed

image

File: source/features/align-issue-labels.css (hunk 11 above)
Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: > gap-1

found in `global.css` with this exact name

File: source/features/align-issue-labels.css [hunk 14]
```diff
@@ -1,3 +1,11 @@
+.rgh-issue-badges:has(> :nth-child(2)) .rgh-issue-type:after {
```
Comment (fregante) [inline source/features/align-issue-labels.css]: We should move this condition to the JS since we have JS. Our usage of :has() has to be limited due to perf concerns.

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: The problem is that labels could be updated in the background

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: Cool, right?

Comment (fregante) [reply source/features/align-issue-labels.css]: Yes but the rest of the logic still lives in the JS anyway, so what happens when they remove the issue type? It's ok if it's slightly inconsistent due to this. I prefer not having "RGH is slow" issues open.

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: The current implementation handles label changes in the background fine; the suggested one would introduce:

- If all labels were removed in the background:  
image
- If labels were added in the background:  
Screenshot 2025-07-09 193233

> so what happens when they remove the issue type?

- If you change the issue type, the type badge updates without moving
- If you remove the issue type, nothing happens
- If you remove the issue type and then add a type, the moved type badge stays in place, but a new one is added. So you can end up with something like this:  
image  
or even this:  
image

Maybe it would be better not to touch the type badges at all

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: > Maybe it would be better not to touch the type badges at all

Or we could move the whole issue type badge container instead (`[class^="IssueTypeIndicator-module__container"]`)

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: > Or we could move the whole issue type badge container instead ([class^="IssueTypeIndicator-module__container"])

Epic fail, this is what happened after removing the issue type in the background:

image

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: So what should we do now?

**Review by BoomchainLabs — APPROVED** [review]

**Review by BoomchainLabs — APPROVED** [review]

File: source/features/align-issue-labels.css (hunk 14 above)
Comment (fregante) [reply source/features/align-issue-labels.css]: Does that error happen consistently? Like if you interact with the list (change page, sorting, add labels)

Comment (fregante) [reply source/features/align-issue-labels.css]: Does that error happen with the current version or only if you move the logic to the JS?

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: Labels are fine; the issue type badges are problematic, and this error only happens when the issue type is removed

> Does that error happen with the current version

No, this error is the result of moving the issue type badge container

Comment (fregante) [reply source/features/align-issue-labels.css]: > with the current version

I mean the current version of this PR, so the answer appears to be "yes"

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: No, in the current version of this PR a different element is moved: https://github.com/refined-github/refined-github/pull/8527/files#diff-90ef46e4a41ff744d8fa919d247b49eae4f2a407fadedb8f2cc3addecdb54cc0R25

Comment (fregante) [reply source/features/align-issue-labels.css]: Let me rephrase that: is this PR currently causing that error in any situation?

Comment (SunsetTechuila) [reply source/features/align-issue-labels.css]: No, this is what it causes:

> * If you remove the issue type, nothing happens
> * If you remove the issue type and then add a type, the moved type badge stays in place, but a new one is added. So you can end up with something like this:
>   image
>   or even this:
>   image

File: source/features/align-issue-labels.tsx [hunk 15]
```diff
@@ -1,16 +1,56 @@
...
+	const mainContent = $('[class^="MainContent-module__inner"]', row);
+	mainContent.classList.add('gap-1');
+	mainContent.append(badges);
+
+	$('[class^="Description-module__container"]', row).style.gap = 'unset';
+
+	const issueType = $optional('[class*="issueTypeTokenContainer"]', row);
+	if (issueType) {
+		issueType.classList.add('rgh-issue-type', 'd-inline-block');
+		badges.prepend(issueType);
```
Comment (fregante) [inline source/features/align-issue-labels.tsx]: So we have to chose between these two:

Screenshot 11

1. either move the type to the last line — and risk an out of date / wrong view when updating the type
2. or leave the type on the second line — and making it look a bit awkward at all times 

I'm leaning towards the ugly bug-free version (2) over the pretty, buggy one (1)

I'm still hoping that GitHub realizes that their mobile app team is just better at design and they follow it so we can drop this feature.

Comment (SunsetTechuila) [reply source/features/align-issue-labels.tsx]: > GitHub realizes that their mobile app team is just better at design

you can't be sure that they moved the badges to the bottom because it makes them easier to read, not because phones don't have much horizontal space)

**Comment by fregante** [comment]
Can you update the readme screenshot with this URL? https://github.com/user-attachments/assets/dca5dc12-7283-4704-a93f-5bfe5f2b1938

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Great! Looking forward to seeing this style again. It was one of the earliest Refined GitHub features

**Comment by kovsu** [comment]
Can we just keep one `bug` label here? It makes me a little bit annoyed.

CleanShot 2025-08-06 at 10 15 20

**Comment by fregante** [comment]
I don’t think we can do that, if people want to use both, it's their fault. 

Maybe open a new feature request to discuss it
