### PR TITLE
Fix `quick-review-comment-deletion`

### LINKED ISSUE #5901: `quick-review-comment-deletion` is broken
### How to replicate the issue

1. Open https://github.com/refined-github/refined-github/pull/5899/files
2. Start a review
3. Try to edit the comment

### Expected

115445792-9fdd6900-a216-11eb-9ba3-6dab4d2f9d32

### Current

Screen Shot 9

### Extension version

22.8.1

### Browser(s) used

Safari

### PR DESCRIPTION
**Pull request by chcamiloam**
Closes #5901 

## Test URLs
https://github.com/refined-github/refined-github/pull/5899/files

## Screenshot

image

### CODE REVIEW

File: source/features/quick-review-comment-deletion.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ function init(signal: AbortSignal): Deinit {
 	delegate(document, '.rgh-review-comment-delete-button', 'click', onButtonClick, {signal});
 	delegate(document, '.rgh-quick-comment-edit-button', 'click', onEditButtonClick, {signal});
 
-	return observe('.review-comment > .unminimized-comment form:not(.js-single-suggested-change-form) .js-comment-cancel-button:not(.rgh-delete-button-added)', {
+	return observe('.review-comment form.js-comment-update:not(.js-single-suggested-change-form) .js-previewable-comment-form .form-actions .js-comment-cancel-button:not(.rgh-delete-button-added)', {
```
Comment (fregante) [inline source/features/quick-review-comment-deletion.tsx:36]: Thanks for the PR!

I think this selector can be greatly shortened now.

Testing:

```suggestion
a
```

File: source/features/quick-review-comment-deletion.tsx [hunk 2]
```diff
@@ -33,7 +33,7 @@ function init(signal: AbortSignal): Deinit {
...
 		add: addDeleteButton,
```
Comment (fregante) [inline source/features/quick-review-comment-deletion.tsx:37]: Testing
```suggestion
		add: addDeleteButton,
```

**Comment by fregante** [comment]
# ཐུགས་རྗེ་ཆེ་
