### PR TITLE
Fix `highest-rated-comment` checkmark misalignment

### LINKED ISSUE #5064: `highest-rated-comment`’s checkmark is misaligned
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Our checkmark is 1px higher than the emoji picker

Screen Shot 3

### Example URL

https://github.com/evanw/esbuild/issues/297#issuecomment-692571427

### Browser(s) used

safari

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5064 

## Test URLs
https://github.com/evanw/esbuild/issues/297#issuecomment-692571427

## Screenshot
image

### CODE REVIEW

File: source/features/highest-rated-comment.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ function highlightBestComment(bestComment: Element): void {
 	select('.unminimized-comment', bestComment)!.classList.add('rgh-highest-rated-comment');
 	select('.unminimized-comment .timeline-comment-header-text', bestComment)!.before(
 		<span
-			className="d-flex flex-items-center color-text-success color-fg-success mr-1 tooltipped tooltipped-n"
+			className="d-inline-block color-text-success color-fg-success mr-1 tooltipped tooltipped-n" // `.d-inline-block` is needed to correctly align with the reaction button #5064
```
Comment (cheap-glitch) [inline source/features/highest-rated-comment.tsx:54]: The wrapper needs `display: inline-block`, otherwise `vertical-align: text-bottom` isn't applied to the icon.

**Review by fregante — APPROVED** [review]
The comment can be dropped, otherwise it's good
