### PR TITLE
Fix `highlight-deleted-and-added-files-in-diffs` on compare page

### LINKED ISSUE #5093: `highlight-deleted-and-added-files-in-diffs` doesn't work on compare pages
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

The file list on compare pages is lazyloaded so `highlight-deleted-and-added-files-in-diffs` doesn't apply:

image

### Example URL

https://github.com/kidonng/xuann.wang/compare/576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by kidonng**
Fix #5093

## Test URLs

[`576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905`#diff-05ed1c7f99](https://github.com/kidonng/xuann.wang/compare/576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873)

## Screenshot

Before:

image

After:

image

### CODE REVIEW

**Comment by cheap-glitch** [comment]
This should probably be fixed by listening for the `load` event of the `include-fragment` instead:

image

This is likely the same solution as in #5066. Also there may be other features affected by this, so a reusable `onCompareDiffLoad` event listener might be useful.

File: source/features/highlight-deleted-and-added-files-in-diffs.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ async function init(): Promise<void | false> {
 	const fileList = await elementReady([
 		'.toc-select details-menu[src*="/show_toc?"]', // `isPR`
 		'.toc-diff-stats + .content', // `isSingleCommit` and `isCompare`
-	].join(','));
+	].join(','), {stopOnDomReady: false});
```
Comment (cheap-glitch) [inline source/features/highlight-deleted-and-added-files-in-diffs.tsx:25]: This should probably be fixed by listening for the `load` event of the `include-fragment` instead:

image

This is likely the same solution as in #5066. Also there may be other features affected by this, so a reusable `onCompareDiffLoad` event listener might be useful.

File: source/features/highlight-deleted-and-added-files-in-diffs.tsx [hunk 2]
```diff
@@ -61,11 +57,14 @@ async function init(): Promise<void | false> {
 	deinit.push(observer.abort);
 }
 
+function initCompare(): void {
+	onDiffFileLoad(init);
+}
```
Comment (cheap-glitch) [inline source/features/highlight-deleted-and-added-files-in-diffs.tsx:62]: Maybe this could be replaced by `additionalListeners` + `additionalListenersOnly` in the `feature.add()`?

Comment (kidonng) [reply source/features/highlight-deleted-and-added-files-in-diffs.tsx:62]: Good to know that!

**Review by cheap-glitch — APPROVED** [review]
Tested on Firefox :100:
