### PR TITLE
Fix token expiration date parsing in Safari

### LINKED ISSUE #9043: "number argument must be finite" when entering personal token in Safari extension
### Description

I see "number argument must be finite" when entering a personal token in the Safari extension options.

Image

I have regenerated my token but I get the same message.

### How to replicate the issue + URL

1. Open the options tab
2. Enter a personal token, then blur the field
3. See the message "number argument must be finite".

### Extension version

26.2.2

### Browser(s) used

Safari 26.3 (21623.2.7.11.6)

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
fixes #9043 

`2026-06-03 19:52:44 UTC` -> `2026-06-03T19:52:44Z`

https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format

https://stackoverflow.com/questions/60816691

### CODE REVIEW

**Comment by fregante** [comment]
Thank you! To avoid whack-a-mole with Date, can you check the docs for the specific date format returned by GitHub (ISO-what?) and how to fully parse it in JavaScript? Ideally including a link in this PR to the GitHub docs and any docs specifying how to parse it?

StackOverflow, like LLM, isn't known for completeness

**Comment by SunsetTechuila** [comment]
✅

**Comment by SunsetTechuila** [comment]
As for the GitHub API docs - they don't mention token expiration date header at all

**Comment by fregante** [comment]
Sigh, you're right: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fdocs.github.com+%22GitHub-Authentication-Token-Expiration%22

It doesn't appear here: https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#headers

It was only announced, without further info: https://github.blog/changelog/2021-07-26-expiration-options-for-personal-access-tokens/

It seems to be exactly what Ruby outputs and the solution here matches what LLMs suggest for this Ruby format.

File: source/options/token-validation.tsx [hunk 1]
```diff
@@ -67,7 +67,9 @@ async function validateToken(): Promise<void> {
 		// Build status message with user and expiration
 		let statusMessage = `👤 @${user}`;
 		if (tokenInfo.expiration) {
-			const msUntilExpiration = new Date(tokenInfo.expiration).getTime() - Date.now();
+			// https://stackoverflow.com/questions/60816691 #9043
+			const expirationDate = new Date(tokenInfo.expiration.replace(' ', 'T').replace(' UTC', 'Z'));
```
Comment (fregante) [inline source/options/token-validation.tsx]: I'd extract this replacements to 

```
const isoString = etc
const date = new Date()
```

Comment (fregante) [reply source/options/token-validation.tsx]: I'd also include a link to my comment above so we know the reasoning behind the code.

Comment (fregante) [reply source/options/token-validation.tsx]: Actually I would do this transformation in the getTokenInfo itself. There's no reason for that Ruby format to exist anywhere in our JS code. 

This means you can undo all changes in source/options/token-validation.tsx

Comment (SunsetTechuila) [reply source/options/token-validation.tsx]: `iso8601String` suggests we could also use a format like `YYYY-MM-DD HH:MM:SSZ`, since the standard allows a space instead of the literal "T" - but we actually can't

File: source/github-helpers/github-token.ts [hunk 2]
```diff
@@ -100,10 +100,13 @@ type TokenInfo = {
 };
 
 export async function getTokenInfo(apiBase: string, personalToken: string): Promise<TokenInfo> {
-	const response = await baseApiFetch({apiBase, token: personalToken, path: ''});
+	const {headers} = await baseApiFetch({apiBase, token: personalToken, path: ''});
+	const expiration = headers.get('GitHub-Authentication-Token-Expiration');
+	// Convert `2026-06-03 19:52:44 UTC` to `2026-06-03T19:52:44Z` #9043
```
Comment (SunsetTechuila) [inline source/github-helpers/github-token.ts]: This comment + issue reference is enough, imo

**Review by fregante — APPROVED** [review]
