### PR TITLE
Restore `forked-to` feature and enable it for every user

### LINKED ISSUE #5596: `forked-to` seems broken
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github

### Extension version

22.4.11

### Browser(s) used

google chrome  100.0.4896.88

### Description

link to your fork button disappears.
* I have cleared cache
* I have my personal token in refined-github
* I have forked refined-github https://github.com/yzqdev/refined-github

link to your fork button disappears.
I guess maybe it's github changed the fork procedure that causes this. Two days before, when I clicked fork button , a dialog jumped, while now when i click fork button, it'll turn to a new fork page.

### after
image

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5596 

## Test URLs

Fork a repo :fork_and_knife:  

## Screenshot

image

### CODE REVIEW

File: source/features/forked-to.tsx [hunk 1]
```diff
@@ -123,7 +117,7 @@ async function init(): Promise<void | false> {
 	}
 
 	// This feature only applies to users that have multiple organizations, because that makes a fork picker modal appear when clicking on "Fork"
-	const hasOrganizations = await elementReady('details-dialog[src*="/fork"]', {waitForChildren: false});
+	const hasOrganizations = select.exists('[data-ga-click*="show fork modal"]');
```
Comment (cheap-glitch) [inline source/features/forked-to.tsx:120]: This targets an attribute on the "Fork" button itself, so we shouldn't need the `elementReady`. Not sure if this is really limited to people in organizations though.

**Review by cheap-glitch — COMMENTED** [review]
@refined-github/maintainers Could someone who's in several organizations test this with multiple forks? Thanks :heart_decoration:

**Comment by fregante** [comment]
GitHub really broke the flow here and I expect them to change this once again soon.

The fork button now **always** points to the new `/fork` page, even if I have a fork.

Big deal breaker: there is NO link to my existing fork. At least I don't see it.

`forked-to` just became _mandatory_ for every GitHub user. 😃

**Comment by fregante** [comment]
Separately perhaps I'd also replace the `?fragment` fetch with an API call because that fragment is no longer shown on GitHub and I expect them to drop it soon (unless they restore it)

File: source/features/forked-to.tsx [hunk 2]
```diff
@@ -123,7 +117,7 @@ async function init(): Promise<void | false> {
 	}
 
 	// This feature only applies to users that have multiple organizations, because that makes a fork picker modal appear when clicking on "Fork"
-	const hasOrganizations = await elementReady('details-dialog[src*="/fork"]', {waitForChildren: false});
+	const hasOrganizations = select.exists('.pagehead-actions [data-ga-click*="show fork modal"]');
```
[the remark this answers is not in the document]
Comment (cheap-glitch) [reply source/features/forked-to.tsx:120]: So just to be clear we can drop the `hasOrganizations` check and just use `fork || isForkedRepo()`, right?

[the remark this answers is not in the document]
Comment (fregante) [reply source/features/forked-to.tsx:120]: Probably! There's no `details` anywhere so anything related to that should be gone.

**Comment by fregante** [comment]
I suppose this will also close https://github.com/refined-github/refined-github/issues/5435

**Comment by cheap-glitch** [comment]
> I suppose this will also close #5435

I don't know, I've never seen this error in the first place

File: source/features/forked-to.tsx [hunk 3]
```diff
@@ -122,12 +116,9 @@ async function init(): Promise<void | false> {
 		await updateUI(forks);
 	}
 
-	// This feature only applies to users that have multiple organizations, because that makes a fork picker modal appear when clicking on "Fork"
-	const hasOrganizations = await elementReady('details-dialog[src*="/fork"]', {waitForChildren: false});
-
 	// Only fetch/update forks when we see a fork (on the current page or in the cache).
 	// This avoids having to `updateCache` for every single repo you visit.
-	if (forks || (hasOrganizations && pageDetect.isForkedRepo())) {
+	if (forks || pageDetect.isForkedRepo()) {
```
Comment (fregante) [inline source/features/forked-to.tsx:121]: Can you flip this condition to allow an early return? I think

```suggestion
	if (!forks && !pageDetect.isForkedRepo()) {
		return false;
	}
```

**Review by fregante — APPROVED** [review]
Feel free to merge and release a new version today

File: source/features/forked-to.tsx (hunk 3 above)
Comment (fregante) [inline source/features/forked-to.tsx:121]: Can you flip this condition to allow an early return? I think

```suggestion
	if (!forks && !pageDetect.isForkedRepo()) {
		return false;
	}
```

Comment (cheap-glitch) [reply source/features/forked-to.tsx:121]: Thought about it too but in this case, since the first block is only one line long, I think it just makes the logic less clear while providing no benefits at runtime.

**Comment by kidonng** [comment]
> GitHub really broke the flow here and I expect them to change this once again soon.

[_The repository fork button now displays existing forks_](https://github.blog/changelog/2022-06-29-the-repository-fork-button-now-displays-existing-forks/).

**Comment by fregante** [comment]
Called it!

Screen Shot 8


> Is this @fregante's work? Impressive 🎉

Screen Shot

First requested in https://github.com/refined-github/refined-github/issues/1129 and implemented in https://github.com/refined-github/refined-github/pull/2153
