### PR TITLE
Show error toast when `quick-label-removal` fails

### LINKED ISSUE #4828: API actions might fail silently
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

On private repositories that are part of a private GitHub org using SAML auth, some features do not work if the token has not been authorized.

This is expected, as there is no workaround other than giving the token access. However, ideally the error would be gracefully handled and feedback given to the user.

For example, when attempting to use the `x` to quickly remove a label from an issue, the button simply appears to do nothing. Opening the Console reveals that the

```http
DELETE /repos/ORG/REPO/issues/NUMBER/labels/LABEL
```

request failed with an unhandled `403` response:

```
Uncaught (in promise) Error: Unable to fetch.
Ensure that your token has access to this repo.
{
	"message": "Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.",
	"documentation_url": "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}
```

Ideally,

- either the features that wouldn't work would just not load
  - and maybe a message would be shown explaining why
- or the user would be notified of the error in some way, with steps to resolve it (as provided by GitHub's response)

### Screenshot

_No response_

### Console errors

```shell
VM256 refined-github.js:2930 DELETE https://api.github.com/repos/ORG/REPO/issues/12345/labels/LABEL 403
mem.cacheKey @ VM256 refined-github.js:2930
async function (async)
mem.cacheKey @ VM256 refined-github.js:2926
(anonymous) @ VM256 refined-github.js:2857
removeLabelButtonClickHandler @ VM256 refined-github.js:8507
listenerFn @ VM256 refined-github.js:1682
VM256 refined-github.js:2906 Uncaught (in promise) Error: Unable to fetch.
Ensure that your token has access to this repo.
{
	"message": "Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.",
	"documentation_url": "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}
    at getError (VM256 refined-github.js:2977)
    at async mem.cacheKey (VM256 refined-github.js:2949)
    at async HTMLHtmlElement.removeLabelButtonClickHandler (VM256 refined-github.js:8507)
```

### Example URL

https://github.com/ORG/REPO/issues/12345

### Browser(s) used

Chrome on macOS

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4828 

## Test URLs

Revoke your API token and try to remove a label on this page.

## Screenshot

https://user-images.githubusercontent.com/46634000/144035109-e9dc3fc6-d729-48b7-bae6-621cf4630cbb.mp4

### CODE REVIEW

File: source/github-helpers/toast.tsx [hunk 1]
```diff
@@ -12,14 +12,14 @@ export function ToastSpinner(): JSX.Element {
...
-	task: TTask,
+type Task<T> = (progress?: ProgressCallback) => Promise<T>;
+export default async function showToast<TaskOrError extends Task<any> | Error>(
+	task: TaskOrError,
 	{
 		message = 'Bulk actions currently being processed.',
 		doneMessage = 'Bulk action processing complete.',
 	} = {},
-): Promise<ReturnType<TTask>> {
+): Promise<[TaskOrError] extends [Task<infer R>] ? R : void> {
```
Comment (cheap-glitch) [inline source/github-helpers/toast.tsx:22]: Since we never use the return value of `showToast`, all those types could be simplified.

File: source/github-helpers/toast.tsx [hunk 2]
```diff
@@ -40,6 +40,10 @@ export default async function showToast<TTask extends Task>(
 	await delay(30); // Without this, the Toast doesn't appear in time
 
 	try {
+		if (task instanceof Error) {
+			throw task;
+		}
+
```
Comment (cheap-glitch) [inline source/github-helpers/toast.tsx:46]: Not sure if that's acceptable, but it's short :sweat_smile:

File: source/features/quick-label-removal.tsx [hunk 3]
```diff
@@ -17,13 +18,23 @@ async function removeLabelButtonClickHandler(event: delegate.Event<MouseEvent, H
 	event.preventDefault();
 
 	const removeLabelButton = event.delegateTarget;
-
 	removeLabelButton.disabled = true;
```
Comment (fregante) [inline source/features/quick-label-removal.tsx:21]: We're now removing the whole label, so no need to disable it

File: source/github-helpers/toast.tsx [hunk 4]
```diff
@@ -12,14 +12,14 @@ export function ToastSpinner(): JSX.Element {
 }
 
 type ProgressCallback = (message: string) => void;
-type Task = (progress?: ProgressCallback) => Promise<unknown>;
-export default async function showToast<TTask extends Task>(
-	task: TTask,
+type Task<T> = (progress?: ProgressCallback) => Promise<T>;
+export default async function showToast<TaskOrError extends Task<any> | Error>(
+	task: TaskOrError,
```
Comment (fregante) [inline source/github-helpers/toast.tsx:17]: I think it should look like this:

```suggestion
type Task = (progress?: ProgressCallback) => Promise<unknown>;
export default async function showToast<TTask extends Task>(
	task: TTask | Error,
```

And then the return `void` as you mentioned.

**Review by fregante — APPROVED** [review]

**Review by fregante — APPROVED** [review]
Name it, read it, tune it, print it, scan it, send it, fax, rename it
Touch it, bring it, pay it, watch it, turn it, leave it, stop, format it

File: source/github-helpers/toast.tsx [hunk 5]
```diff
@@ -40,11 +40,15 @@ export default async function showToast<TTask extends Task>(
...
+		if (task instanceof Error) {
+			throw task;
+		}
+
+		await task(updateToast);
 		toast.classList.replace('Toast--loading', 'Toast--success');
 		updateToast(doneMessage);
 		iconWrapper.firstChild!.replaceWith(<CheckIcon/>);
-		return result;
+		return;
```
[the remark this answers is not in the document]
Comment (cheap-glitch) [reply source/github-helpers/toast.tsx:51]: I left the `return` because I assumed it was there to "avoid" the `finally` block. Is it executed regardless?

[the remark this answers is not in the document]
Comment (busches) [reply source/github-helpers/toast.tsx:51]: If you're in a try block then finally will be executed no matter how you leave it.

**Comment by cheap-glitch** [comment]
We've finally dropped to 40 bugs!  (๑•̀ㅂ•́)و✧

Let's see how long that lasts…
