### PR TITLE
Fix overlap in `rgh-feature-descriptions`

### LINKED ISSUE #6337: Feature description overlaps first line of code on new file viewer
### Description

image

### How to replicate the issue + URL

Happens on any [feature source code](https://github.com/refined-github/refined-github/tree/main/source/features) file. For example: https://github.com/refined-github/refined-github/blob/main/source/features/action-used-by-link.tsx

This does **not** happen when source file is not an feature with an description. For example: https://github.com/refined-github/refined-github/blob/main/build/prepare-safari-release.sh

### Extension version

23.2.11

### Browser(s) used

Firefox

### PR DESCRIPTION
**Pull request by amanmalh**
Fixes #6337 

## Test URLs
https://github.com/refined-github/refined-github/blob/main/source/features/action-used-by-link.tsx

## Screenshot
feature-description-overlap

### CODE REVIEW

File: source/features/rgh-feature-descriptions.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ async function add(infoBanner: HTMLElement): Promise<void> {
 	conversationsUrl.searchParams.set('q', `sort:updated-desc "${feature.id}"`);
 
 	infoBanner.before(
-		<div className="Box mb-3">
+		<div className="Box mb-3 d-inline-block width-full">
```
Comment (fregante) [inline source/features/rgh-feature-descriptions.tsx:25]: Thank you! Can you also add a comment? It's not immediately clear why they're there
```suggestion
		{/* Block and width classes required to avoid margin collapse */}
		<div className="Box mb-3 d-inline-block width-full">
```

**Review by fregante — APPROVED** [review]
