### PR TITLE
`clean-repo-filelist-actions` - Restore feature

### LINKED ISSUE #9122: `clean-repo-filelist-actions` is broken
### Description

Branch name reduced to a single letter 😕

Image

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

26.3.21

### Browser(s) used

Chrome

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by fregante**
- fixes https://github.com/refined-github/refined-github/issues/9122

 

## Test URLs
https://github.com/refined-github/refined-github

## Screenshot

Screenshot 32

Screenshot 31

### CODE REVIEW

File: source/features/clean-repo-filelist-actions.tsx [hunk 1]
```diff
@@ -1,63 +1,8 @@
...
-		<div className="tooltipped tooltipped-n" aria-label={tooltip} />,
-	);
-}
-
-function cleanFilelistActions(addFileButton: Element): void {
-	const container = addFileButton.parentElement!.parentElement!;
-	const codeButton = $optional('& > button', container);
-	container.classList.add('rgh-clean-repo-filelist-actions');
-
-	cleanAddFileButton(addFileButton);
```
Comment (fregante) [inline source/features/clean-repo-filelist-actions.tsx:24]: Implemented by GitHub in smaller viewports 👍

File: source/features/clean-repo-filelist-actions.tsx [hunk 2]
```diff
@@ -1,63 +1,8 @@
...
-
-	if (!pageDetect.isRepoRoot() || !codeButton) {
-		return;
-	}
-
-	cleanCodeButton(codeButton);
```
Comment (fregante) [inline source/features/clean-repo-filelist-actions.tsx:30]: This can now be done via CSS.

File: source/features/clean-repo-filelist-actions.tsx [hunk 3]
```diff
@@ -1,63 +1,8 @@
...
-import PlusIcon from 'octicons-plain-react/Plus';
-import {$, $optional} from 'select-dom/strict.js';
-
-import features from '../feature-manager.js';
-import {assertNodeContent, wrap} from '../helpers/dom-utils.js';
-import observe from '../helpers/selector-observer.js';
 import './clean-repo-filelist-actions.css';
 
-/** Add tooltip on a wrapper to avoid breaking dropdown functionality */
-function addTooltipToSummary(childElement: Element, tooltip: string): void {
```
Comment (fregante) [inline source/features/clean-repo-filelist-actions.tsx:12]: GitHub hides a label and doesn't add any tooltips. I reckon we can do the same.

_However_ maybe we should also replicate the responsive behavior: only hide "Code" in small windows?

File: source/features/clean-repo-filelist-actions.css [hunk 4]
```diff
@@ -1,8 +1,24 @@
...
-		width: 0;
+		span[data-component='text'] {
+			display: none;
+		}
+	}
+
+	/* Hide agent */
+	button:has(svg.octicon-agent) {
+		display: none;
+	}
```
Comment (fregante) [inline source/features/clean-repo-filelist-actions.css:21]: I found no button that triggers the exact same UI. 

The button in the header with the same icon opens a popup with textarea that seemingly does the same thing, but the UI is different.

I think they're functionally the same so I'm hiding this one.

**Comment by fregante** [comment]
Parts of this were actually implemented by GitHub, see the old UI:

Screenshot 33



versus the new UI. Notice how they also started using the Code icon like we did:

Screenshot 34

**Comment by SunsetTechuila** [comment]
image

File: source/features/clean-repo-filelist-actions.css [hunk 5]
```diff
@@ -1,8 +1,24 @@
-.rgh-clean-repo-filelist-actions .TextInput-wrapper {
-	/* Override the value that GitHub sets */
-	min-width: unset !important;
+html:not([rgh-OFF-clean-repo-filelist-actions]) div[class^='OverviewContent'] {
+	/* Hide "Code" label */
+	[data-variant='primary'] {
+		padding-inline: 0.5em 0.4em; /* Reduce and balance padding */
+		span[data-component='leadingVisual'] {
+			margin-right: 0.2em;
```
Comment (SunsetTechuila) [inline source/features/clean-repo-filelist-actions.css]:
```suggestion
			margin-right: 0.2em;

			> .octicon-code {
				display: inline-block !important;
			}
```

https://github.com/refined-github/refined-github/pull/9265#issuecomment-4322262324

File: source/features/clean-repo-filelist-actions.css [hunk 6]
```diff
@@ -1,8 +1,24 @@
...
 
-	input:not(:focus) {
-		width: 0;
+		span[data-component='text'] {
+			display: none;
+		}
+	}
+
+	/* Hide agent */
+	button:has(svg.octicon-agent) {
```
Comment (SunsetTechuila) [inline source/features/clean-repo-filelist-actions.css]:
```suggestion
	button:has(> .octicon-agent) {
```

File: source/features/clean-repo-filelist-actions.css [hunk 7]
```diff
@@ -1,8 +1,24 @@
-.rgh-clean-repo-filelist-actions .TextInput-wrapper {
-	/* Override the value that GitHub sets */
-	min-width: unset !important;
+html:not([rgh-OFF-clean-repo-filelist-actions]) div[class^='OverviewContent'] {
+	/* Hide "Code" label */
+	[data-variant='primary'] {
```
Comment (SunsetTechuila) [inline source/features/clean-repo-filelist-actions.css]:
```suggestion
	button[data-variant='primary'] {
```

**Comment by fregante** [comment]
Thanks for fixing it!

**Comment by fregante** [comment]
You should pick one 😃 

Screenshot

**Comment by SunsetTechuila** [comment]
It's GitHub that should stop using my non-public email for suggestions

**Comment by fregante** [comment]
There's a setting for that (I thought)
