### PR TITLE
Fix `conflict-marker` duplicated

### LINKED ISSUE #6809: `conflict-marker` duplicated
### Description

`conflict-marker`'s warning button is duplicating when page back.

image

### How to replicate the issue + URL

1. https://github.com/pulls
2. Go to any page.
3. Go back to previous page

### Extension version

23.7.25

### Browser(s) used

Chrome 115.0.5790.114 (arm64)

### PR DESCRIPTION
**Pull request by 134130**
## Description
- Closes #6809
- Use new patterns
  - element observing
  - seperate gql

## Test URLs
- https://github.com/pulls
- https://github.com/refined-github/refined-github/pulls

## Screenshot
image

### CODE REVIEW

**Comment by fregante** [comment]
This unfortunately triggers 25 HTTP requests every time you open the pull requests page, which isn't acceptable. We need to use `batched-function` to compose the old GraphQL call and inside it add the icons to the DOM. I don’t think we used this exact pattern in the extension yet but we need to start. The .gql file cannot be used in this case because of the composed GraphQL call.

**Comment by 134130** [comment]
> This unfortunately triggers 25 HTTP requests every time you open the pull requests page, which isn't acceptable. We need to use `batched-function` to compose the old GraphQL call and inside it add the icons to the DOM. I don’t think we used this exact pattern in the extension yet but we need to start. The .gql file cannot be used in this case because of the composed GraphQL call.

Ok I'll make bunch API call as it was before

File: source/features/conflict-marker.tsx [hunk 1]
```diff
@@ -72,25 +51,22 @@ async function init(): Promise<false | void> {
 	}
 }
 
+function init(signal: AbortSignal): void {
+	observe('#js-issues-toolbar', addConflictMarkers, {signal});
```
Comment (fregante) [inline source/features/conflict-marker.tsx:55]: What is this element? Does it exist on the milestones page? Does it work there now?

File: source/features/conflict-marker.tsx [hunk 2]
```diff
@@ -1,63 +1,42 @@
...
 			}
 		}
 	`;
 }
 
-function buildQuery(prs: PRConfig[]): string {
-	return prs.map(pr => createQueryFragment(pr)).join('\n');
-}
+async function addConflictMarkers(container: HTMLDivElement): Promise<void> {
+	const links = select.all('.js-issue-row:has(.octicon-git-pull-request.color-fg-open) a.js-navigation-open', container);
```
Comment (fregante) [inline source/features/conflict-marker.tsx:23]: The feature will likely fail when there are 0 links

File: source/features/conflict-marker.tsx (hunk 1 above)
Comment (134130) [reply source/features/conflict-marker.tsx:55]: It works ;)
image

File: source/features/conflict-marker.tsx (hunk 2 above)
Comment (134130) [reply source/features/conflict-marker.tsx:23]: Thank you! It was fixed.

File: source/features/conflict-marker.tsx (hunk 1 above)
Comment (fregante) [reply source/features/conflict-marker.tsx:52]: I think this will fail on slower connections because the observer will call the callback as soon as `#js-issues-toolbar` is found, but at that point the long list of PRs might not be done downloading yet. This is why I was suggesting to use batched-function and the link selector

```js
const addIcon = batchedFunction((icons) => {
  // create query, etc
});

observe('.js-issue-row:has(.octicon-git-pull-request.color-fg-open) a.js-navigation-open', addIcon, {signal})
```

Comment (134130) [reply source/features/conflict-marker.tsx:52]: 🤔 I've tested a lot but It can detect icons successly. But I'll test more slow network conditions.
And is your suggestion works correctly? As I know, the selector-observe only works as single element, not all elements.

Comment (fregante) [reply source/features/conflict-marker.tsx:52]: > As I know, the selector-observe only works as single element, not all elements

No, the observer detects any and all elements that appear on the page until the next page load.

Here's what happens with the suggested code:

1. `observe` finds 3 elements
2. calls `addIcon` once per element
3. batched function then calls the anonymous function with a single array: `[prLink1, prLink2, prLink3]`
4. you can use this array to construct the GQL call
5. if more items are detected later, it repeats from step 1

On fast connections maybe batchedFunction will call the function with 25 items, on slower connections it'll make multiple API calls, that's ok

Comment (134130) [reply source/features/conflict-marker.tsx:52]: Exactly, that was I thought.
I'm just wondering is there existing some utility function: batchedFunction, and the batchedFunction's throttle (or debounce) time.

Comment (fregante) [reply source/features/conflict-marker.tsx:52]: What do you mean? It does exist and we're already using it. We don't need to change it at this point https://github.com/Richienb/batched-function

**Comment by fregante** [comment]
Nice, that looks pretty simple to implement in more features

**Review by fregante — APPROVED** [review]

File: source/features/conflict-marker.tsx [hunk 3]
```diff
@@ -1,96 +1,65 @@
...
-	deduplicate: 'has-rgh',
-	awaitDomReady: true, // TODO: Use observe + batched-function
 	init,
 });
+
+/*
+Test URLs
+https://github.com/pulls
+https://github.com/refined-github/sandbox/issues?q=conflict
+https://github.com/kubernetes/kubernetes/milestone/62
```
Comment (fregante) [inline source/features/conflict-marker.tsx:64]: This section exists to simplify testing so we should try to use URLs that do and always will include the feature. Our sandbox repo is where these scenarios exist and can be created.

File: source/features/conflict-marker.tsx [hunk 4]
```diff
@@ -1,96 +1,65 @@
...
-				</a>,
+					<AlertIcon className="v-align-middle" />
+				</a>
 			);
 		}
 	}
 }
 
+function init(signal: AbortSignal): void {
+	observe('.js-issue-row:has(.octicon-git-pull-request.color-fg-open) a.js-navigation-open', batchedFunction(addIcon, {delay: 100}), {signal});
```
Comment (fregante) [inline source/features/conflict-marker.tsx:47]: Without a `delay` it's too fast even for high-speed internet:

Screenshot

100ms seems to fix it:

Screenshot 1



We have 2 more functions that use `batchedFunction` and likely suffer the same issue. PR welcome in that case too, inlining the `batchedFunction()` call this way

**Review by fregante — APPROVED** [review]
