### PR TITLE
`jump-to-conversation-close-event` - Restore on PRs

### LINKED ISSUE #9248: `jump-to-conversation-close-event` broken on new PR view
See context in https://github.com/refined-github/refined-github/issues/8946

### Test URL

https://github.com/refined-github/sandbox/pull/1

### PR DESCRIPTION
**Pull request by fregante**
- Closes https://github.com/refined-github/refined-github/issues/9248

## Test URLs

https://github.com/refined-github/refined-github/pull/9231

## Screenshot

GitHub has a couple of bugs around scrolling to the event but that's not this feature's responsibility to fix

gif233

### CODE REVIEW

File: source/features/jump-to-conversation-close-event.tsx [hunk 1]
```diff
@@ -11,6 +11,8 @@ import observe from '../helpers/selector-observer.js';
 import './jump-to-conversation-close-event.css';
 
 export const statusBadgeSelector = [
+	'span[class*="StateLabel"]',
+	// TOdO: Drop both in September 2026
```
Comment (SunsetTechuila) [inline source/features/jump-to-conversation-close-event.tsx:15]:
```suggestion
	// TOdO: dRoP bOtH iN sEpTeMbEr 2026
```

**Review by SunsetTechuila — APPROVED** [review]
I have a similar commit, but I don't really remember why I haven't opened a PR. If there were any gotchas, I can't find them now

**Comment by SunsetTechuila** [comment]
Judging by the dates, I decided to fix the `locked-issue` first, but that took two weeks and I forgot to return to `jump-to-conversation-close-event`
