### PR TITLE
`bugs-tab` - Support Bug type

### LINKED ISSUE #8227: Support for Github Issue Types in `bugs-tab`
### Description

One of the nice features of refined-github is that it has the cool "Bugs" tab:

Image

which I believe is `bugs-tab`. However, recently GitHub has enabled for GA (or at least many repos) the Issue types:

https://github.blog/changelog/2025-01-13-evolving-github-issues-public-preview/

And one of my orgs/repos was one that got it, and as [you'll see](https://github.com/GEOS-ESM/MAPL/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) I have replaced our old "Bug" label to use the new "Bug" issue type:

Image

But on that page, I have `bugs-tab` enabled, but no "Bugs" tab is made. I believe this is because `bugs-tab` looks only at labels.

So I was wondering, can we get support for both Bug-as-label and Bug-as-issue-type in `bugs-tab`?

(And I suppose, would there a be a reason to make a `Feature` and `Task` tab? Those are the other types of Issues now available.)

### Example URLs

https://github.com/GEOS-ESM/MAPL/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

### PR DESCRIPTION
**Pull request by Pixxle**
Closes #8227

Not the best at crafting regexp, so would appreciate suggestions on how to improve it if possible, but all existing tests on queryPartsRegExp are still passing.

## Test URLs
https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+%28label%3Abug+OR+type%3ABug%29

Unfortunately don't have any public repository available to test the issue type bug on. 

## Screenshot

image

image

### CODE REVIEW

File: source/features/bugs-tab.tsx [hunk 1]
```diff
@@ -49,7 +51,7 @@ const bugs = new CachedFunction('bugs', {
 
 async function getSearchQueryBugLabel(): Promise<string> {
 	const {label} = await bugs.getCached() ?? {};
-	return 'label:' + SearchQuery.escapeValue(label ?? 'bug');
+	return `(label:${label ?? 'bug'} OR type:Bug)`;
```
Comment (fregante) [inline source/features/bugs-tab.tsx:54]: Don't drop the escape

File: source/features/bugs-tab.tsx [hunk 2]
```diff
@@ -24,20 +24,22 @@ type Bugs = {
 async function countBugs(): Promise<Bugs> {
 	const {repository} = await api.v4(CountBugs);
 
+	const issuesBugCount = repository.issues.totalCount ?? 0;
+
 	// Prefer native "bug" label
```
Comment (fregante) [inline source/features/bugs-tab.tsx:29]: Can you simplify this setup? I'd rather see:

```JS
const label = repository.labels.find( etc ) ?? 'bug'
const count = repository.labels.find( etc ) ?? 0
return {label, count: count + issuesBugCount}
```

File: source/features/bugs-tab.tsx [hunk 3]
```diff
@@ -24,20 +24,22 @@ type Bugs = {
 async function countBugs(): Promise<Bugs> {
 	const {repository} = await api.v4(CountBugs);
 
+	const issuesBugCount = repository.issues.totalCount ?? 0;
```
Comment (fregante) [inline source/features/bugs-tab.tsx:27]:
```suggestion
	const bugTypeCount = repository.issues.totalCount ?? 0;
```

File: source/github-helpers/search-query.ts [hunk 4]
```diff
@@ -1,4 +1,4 @@
-const queryPartsRegExp = /(?:[^\s"]|"[^"]*")+/g;
+const queryPartsRegExp = /[^\s"()]+:[^"\s()]*(?:"[^"]*")?|\([^)]*\)|"[^"]*"|[^\s"():]+/g;
```
Comment (fregante) [inline source/github-helpers/search-query.ts:1]: Oof this is a mouthful. Would be good to add more tests with and without parents to see how it behaves

**Review by fregante — COMMENTED** [review]
Thank you for the PR!

File: source/github-helpers/search-query.ts (hunk 4 above)
Comment (Pixxle) [reply source/github-helpers/search-query.ts:1]: Yeah, the regex isn't beautiful, I'll add tests for different cases en scenarios!

**Comment by Pixxle** [comment]
> Thank you for the PR!

Of course, I'll take a look at all your suggestions in the coming week!

File: source/features/bugs-tab.tsx [hunk 5]
```diff
@@ -49,7 +57,7 @@ const bugs = new CachedFunction('bugs', {
 
 async function getSearchQueryBugLabel(): Promise<string> {
 	const {label} = await bugs.getCached() ?? {};
-	return 'label:' + SearchQuery.escapeValue(label ?? 'bug');
+	return `(label:${SearchQuery.escapeValue(label ?? 'bug')} OR type:Bug)`;
```
Comment (fregante) [inline source/features/bugs-tab.tsx:60]: My main concern with this is that selecting the `bug` label will no longer activate the "bugs" tab

Screenshot

But that's ok because now that's not enough to show all bugs in the repo. Thanks GitHub.

**Review by fregante — APPROVED** [review]
YOLO

**Comment by fregante** [comment]
@Pixxle thank you for working on this?
