### PR TITLE
Fix: `profile-gists-link` is not responsive

### LINKED ISSUE #5184: `profile-gists-link` is not responsive
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

https://user-images.githubusercontent.com/44045911/145593519-f93e98f0-001f-4df0-b0e6-b3b5dca18dd3.mov

### Example URL

https://github.com/kidonng

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5184 

## Test URLs
https://togithub.com/kidonng

## Screenshot

https://user-images.githubusercontent.com/46634000/147740681-f809893b-e2e0-4d28-802b-7c0423f21847.mp4

### CODE REVIEW

**Review by amerixan — APPROVED** [review]
lgtm

**Review by fregante — COMMENTED** [review]
Untested but, do we also need a *trigger* to alert the widget to possibly immediately hide it? Let's say we add this link but the window is already at 700px

File: source/features/profile-gists-link.tsx [hunk 1]
```diff
@@ -27,13 +29,25 @@ async function init(): Promise<void> {
...
+		>
 			<CodeSquareIcon className="UnderlineNav-octicon hide-sm"/>
 			{' Gists '}
 		</a>
 	);
 
-	(await elementReady('.UnderlineNav-body'))!.append(link);
+	const navigationBar = (await elementReady('.UnderlineNav-body'))!;
+	navigationBar.append(link);
+	navigationBar.replaceWith(navigationBar);
```
Comment (cheap-glitch) [inline source/features/profile-gists-link.tsx:46]: > Untested but, do we also need a _trigger_ to alert the widget to possibly immediately hide it? Let's say we add this link but the window is already at 700px

This is what this line is here for (I copied it from `releases-tab`).
