### PR TITLE
Restore `quick-new-issue` on Global navigation update

### LINKED ISSUE #6455: `quick-new-issue` broken on "Global navigation update"
### Description

Screenshot 2

```
refined-github.js:3727 📕 0.0.0 → TypeError: Cannot read properties of null (reading 'textContent')
    at Module.isArchivedRepo (refined-github.js:26112:90)
    at isArchivedRepoAsync (refined-github.js:18131:60)
    at async init (refined-github.js:12525:7)
    at async runFeature (refined-github.js:3797:16)
    at async setupPageLoad (refined-github.js:3809:5)
```

### How to replicate the issue + URL

Every page, including this issue

### Extension version

23.3.2, 23.3.31

### Browser(s) used

Safari, Chrome

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #6455 

## Test URL

here

## Demo

Screenshot 27

## Missing

- [ ] https://github.com/refined-github/github-url-detection/pull/167

### CODE REVIEW

File: source/github-helpers/index.ts [hunk 1]
```diff
@@ -177,7 +177,7 @@ export function shouldFeatureRun({
 
 export async function isArchivedRepoAsync(): Promise<boolean> {
 	// Load the bare minimum for `isArchivedRepo` to work
-	await elementReady('#repository-container-header');
+	await elementReady('main > div');
```
Comment (fregante) [inline source/github-helpers/index.ts:180]: This should work for both. The first `div` in `main` appears to always be the flash banner itself or some other empty element if the banner is missing.

I can't use `main` because that would wait for the whole page before ever resolving, whether the banner exists or not
