### PR TITLE
`reactions-avatars`, `small-user-avatars` - Fix Copilot user

### LINKED ISSUE #8864: `reactions-avatars` shows bad icon for copilot
### Description

Image

When you mention copilot, it will leave a temporary reaction. The avatar we show is wrong 

### How to replicate the issue + URL

https://github.com/refined-github/shorten-repo-url/pull/70#issuecomment-3734370625

### Extension version

25.11.4

### Browser(s) used

Safari

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
resolves #8864

## Test URLs

https://github.com/refined-github/refined-github/issues/7761

https://github.com/aio-libs/aiohttp/pull/3809#issuecomment-498809698

https://github.com/refined-github/refined-github/pull/8848#issuecomment-3732149089

## Screenshot

image

image

image

### CODE REVIEW

File: source/features/small-user-avatars.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ function addAvatar(link: HTMLElement): void {
 }
 
 function addMentionAvatar(link: HTMLAnchorElement): void {
-	const username = link.href.split('/').pop()!;
+	const username = link.textContent.slice(1);
```
Comment (fregante) [inline source/features/small-user-avatars.tsx]: Feels like we did the opposite a few years ago. Worth a git blame on this line

Comment (SunsetTechuila) [reply source/features/small-user-avatars.tsx]: Nice catch. #8389

Comment (SunsetTechuila) [reply source/features/small-user-avatars.tsx]: Do we really need to support hovercards? Maybe we can just return if a mention is truncated?

Comment (fregante) [reply source/features/small-user-avatars.tsx]: I think it's not too much trouble to drop /apps/ or whatever appears in bots' URLs. The copilot-specific exception is fine too if it's only one. 

Either way it's worth leaving a comment pointing to that PR explaining why we don't use textContent

File: source/github-helpers/get-user-avatar.ts [hunk 2]
```diff
@@ -2,25 +2,25 @@ import {$optional} from 'select-dom/strict.js';
...
-	// Find image on page. Saves a request and a redirect + add support for bots
+	// Find image on page. Saves a request and a redirect
 	const existingAvatar = $optional(`[href="/${cleanName}" i] img`);
-
 	if (existingAvatar) {
 		return existingAvatar.src;
 	}
 
-	// If it's not a bot, use a shortcut URL #2125
-	if (cleanName === username) {
```
Comment (SunsetTechuila) [inline source/github-helpers/get-user-avatar.ts:19]: It's technically possible for bots to have a name/avatar different from the user or organization that registered them, so `https://avatars.githubusercontent.com/${cleanName}` won't work in those cases. Still, I consider that scenario rare enough for bots that leave reactions (I couldn't find any examples) that it's probably not worth accounting for it

File: source/features/small-user-avatars.tsx [hunk 3]
```diff
@@ -40,7 +40,7 @@ function initOnce(): void {
 			[data-testid="closed-at"]
 		) a[data-hovercard-url*="/users"]`, // `isIssueList`
 	], addAvatar);
-	observe('.user-mention:not(.commit-author)[data-hovercard-type="user"]', addMentionAvatar);
+	observe('.user-mention:not(.commit-author)', addMentionAvatar);
```
Comment (SunsetTechuila) [inline source/features/small-user-avatars.tsx]: Is this something we want?

image

Comment (fregante) [reply source/features/small-user-avatars.tsx]: Sure I think it makes sense

File: source/github-helpers/get-user-avatar.ts [hunk 4]
```diff
@@ -1,7 +1,11 @@
 import {$optional} from 'select-dom/strict.js';
 import * as pageDetect from 'github-url-detection';
+import CopilotIcon from 'octicons-plain-react/Copilot';
```
Comment (fregante) [inline source/github-helpers/get-user-avatar.ts]: Why? Can't we load the image from GitHub somewhere? I don't want this extra complexity for little improvement

Comment (SunsetTechuila) [reply source/github-helpers/get-user-avatar.ts]: > for little improvement

On my main monitor (27" QHD) raster Copilot avatar is barely readable (the screenshots attached are 150% zoom). But alright, reverted

Comment (SunsetTechuila) [reply source/github-helpers/get-user-avatar.ts]: Good that this change didn't make it into the main branch

>  raster Copilot avatar is barely readable

It's much better now:

image
