### PR TITLE
Fix VIP label check for low quality comments

### LINKED ISSUE #6799: `hide-low-quality-comments` hides comment by owner
### Description

Hidden comment:

<details>
<summary>Large image</summary>

329F6369-7E49-4A22-AA77-215C41F45E7B

</details>

Revealing shows it’s by a maintainer:

<details>
<summary>Large image</summary>

E03C341C-714E-4BB2-8818-27ADD7A706D4

</details>

### How to replicate the issue + URL

https://github.com/sindresorhus/type-fest/issues/621

### Extension version

23.6.17

### Browser(s) used

Safari iOS 16.3

### PR DESCRIPTION
**Pull request by DerTimonius**
Hi everyone, thanks for the great extension!

## Description

This PR will fix the "VIP label" check to still show "low quality" comments if it was posted by a VIP like owner, maintainer, author etc. 
closes #6799 

## How
The previous check is not working since the `.timeline-comment-label` has been removed at some point. The code now checks for the `.Label` class that is given to labels and then tests the innerHTML to be one of the VIPs defined in an array above.

## Test URLs
https://github.com/sindresorhus/type-fest/issues/621 -> comment by repo owner is now shown
https://github.com/oslabs-beta/ReacTree/issues/35 -> if low quality comment was posted by non-VIP, comment is hidden

## Screenshot

current behavior
image

behavior with PR
image

### CODE REVIEW

File: source/features/hide-low-quality-comments.tsx [hunk 1]
```diff
@@ -62,7 +62,9 @@ function init(): void | false {
 		// Ensure that they're not by VIPs (owner, collaborators, etc)
 		// TODO: use :has()
 		const comment = commentText.closest('.js-timeline-item')!;
-		if (select.exists('.timeline-comment-label', comment)) {
+		const vips = ["Owner", "Author", "Maintainer", "Member", "Contributor"];
```
Comment (DerTimonius) [inline source/features/hide-low-quality-comments.tsx:65]: List may be incomplete

File: source/features/hide-low-quality-comments.tsx [hunk 2]
```diff
@@ -62,7 +62,9 @@ function init(): void | false {
 		// Ensure that they're not by VIPs (owner, collaborators, etc)
 		// TODO: use :has()
 		const comment = commentText.closest('.js-timeline-item')!;
-		if (select.exists('.timeline-comment-label', comment)) {
+		const vips = ['Owner', 'Author', 'Maintainer', 'Member', 'Contributor'];
+		const label = select('.Label', comment);
+		if (label && vips.includes(label.innerHTML)) {
```
Comment (fregante) [inline source/features/hide-low-quality-comments.tsx:67]: You can use .textContent

**Review by fregante — COMMENTED** [review]
Thank you! Are sure it’s not possible via class? I think it still has a generic “.Label” class

**Comment by DerTimonius** [comment]
@fregante You're right, it also works if the code just checks if the `.Label` class exists. I thought yesterday that it was the same class that was used for the reactions, but it was late, I was tired 😉 
Changed the code now to run `select.exists` instead of checking the text value of the label!

**Review by fregante — APPROVED** [review]

**Comment by DerTimonius** [comment]
@fregante Thanks for approving this PR! 🙌 
Is there anything missing to get this merged? 😊
