### PR TITLE
Fix linkified `use-first-commit-message-for-new-prs`

### LINKED ISSUE #5382: `use-first-commit-message-for-new-prs` breaks when commit summary contains link
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/BNFC/bnfc/pull/new/layout-error

(But this URL could soon not demonstrate the problem any more, as the state of the repo changes.)

### Extension version

22.2.1

### Browser(s) used

Google Chrome

### Description

If I open a new PR from a branch whose first commit starts with `Re #<issue>: text`, then the PR title is just `Re`.

I'd like to keep the full title.
Ideally, the PR text would be made from all of the commit titles.  (I dimly remember that this used to be the case once, but then disappeared as a feature.)

Screenshot 2022-02-08 at 18 43 36

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5382 

Also restores using the commit description as the PR body.

## Test URLs

- https://togithub.com/refined-github/sandbox/compare/first-commit-msg?expand=1
- https://togithub.com/BNFC/bnfc/compare/master...176-source-position?expand=1
- https://togithub.com/refined-github/refined-github/compare/add-multiple-prs-dropdown?expand=1

## Screenshot

With the following commits:

image

**Before**

before-pr-message

**After**

after-pr-message

### CODE REVIEW

File: source/features/use-first-commit-message-for-new-prs.tsx [hunk 1]
```diff
@@ -6,25 +6,38 @@ import * as textFieldEdit from 'text-field-edit';
...
+		return select('#commits_bucket [data-url$="compare/commit"] a[title]')!.title.split('\n\n');
+	}
+
+	// Linkified commit summaries are split into several adjacent links #5382
+	const commitSummary = select.all('#commits_bucket .js-commits-list-item:first-child .js-details-container > p > a')
+		.map(commitTitleLink => commitTitleLink.innerHTML)
+		.join('')
+		.replace(/<\/?code>/g, '`');
+
+	const commitDescription = select('#commits_bucket .js-commits-list-item pre')?.textContent ?? '';
```
Comment (kidonng) [inline source/features/use-first-commit-message-for-new-prs.tsx:21]: `#commits_bucket` seems unnecessary if you are targeting `.js-commits-list-item`.

File: source/features/use-first-commit-message-for-new-prs.tsx [hunk 2]
```diff
@@ -6,25 +6,38 @@ import * as textFieldEdit from 'text-field-edit';
...
 import looseParseInt from '../helpers/loose-parse-int';
 
+// TODO [2022-05-01]: Drop GHE code and merge function back in init
+function getFirstCommitMessage(): string[] {
+	if (pageDetect.isEnterprise()) {
+		return select('#commits_bucket [data-url$="compare/commit"] a[title]')!.title.split('\n\n');
+	}
+
+	// Linkified commit summaries are split into several adjacent links #5382
+	const commitSummary = select.all('.js-commits-list-item:first-child .js-details-container > p > a')
```
Comment (cheap-glitch) [inline source/features/use-first-commit-message-for-new-prs.tsx:16]: This selector isn't great. Maybe we should keep `a.Link--primary` and do a second `select` on its `parentElement`.
