### PR TITLE
`unread-anywhere` - Restore button

### LINKED ISSUE #9154: `unread-anywhere` broken (button missing)
### Description

Image

### How to replicate the issue + URL

✨ anywhere ✨

### Extension version

26.3.21

### Browser(s) used

Safari 18.4

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #9154 

## Test URLs

_anywhere_

## Screenshot

1. Load with notifications 
2. Indicator disappears when clicking
3. Indicator reappears when there are new notifications	

All happens without glitches or duplication

gif2

### CODE REVIEW

File: source/features/unread-anywhere.tsx [hunk 1]
```diff
@@ -46,8 +57,8 @@ async function openUnreadNotifications(event?: React.MouseEvent): Promise<void>
 			updateToast(`Opened the last ${limit} unread notifications`);
 		} else {
 			updateToast(pluralize(urls.length, '$$ notification') + ' opened');
-			// Update the UI too. Optional because the UI is often out of date
-			$optional('.AppHeader-button--hasIndicator')?.classList.remove('AppHeader-button--hasIndicator');
+			// Update the UI too
+			removeNotificationIndicator($(buttonWithNotificationsSelector));
```
Comment (fregante) [inline source/features/unread-anywhere.tsx:62]: Reportedly the UI no longer gets out of date. This expectation is low-risk anyway, best case scenario we get notified of out of date UIs.

File: source/features/unread-anywhere.tsx [hunk 2]
```diff
@@ -59,39 +70,44 @@ async function openUnreadNotifications(event?: React.MouseEvent): Promise<void>
...
-	// Reverse order so that the new button is painted below the "unread indicator"
-	nativeLink.parentElement!.classList.add('d-flex', 'flex-row-reverse');
-	nativeLink.classList.add('AppHeader-buttonLeft');
 	const button = (
 		<button
 			type="button"
 			onClick={openUnreadNotifications}
 			// Show pointer cursor even when disabled
-			style={{width: 10, cursor: 'pointer'}}
+			style={{width: 14, cursor: 'pointer'}}
```
Comment (fregante) [inline source/features/unread-anywhere.tsx:81]: Padding is gone from classes

File: source/features/unread-anywhere.tsx [hunk 3]
```diff
@@ -59,39 +70,44 @@ async function openUnreadNotifications(event?: React.MouseEvent): Promise<void>
...
+
 	nativeLink.before(button);
+	button.setAttribute('data-variant', 'invisible'); // Enables hover style
 	button.classList.add(
 		...classes,
-		'AppHeader-buttonRight',
 		'tooltipped',
 		'tooltipped-sw',
+		'rounded-left-0',
+		'border-left-0',
```
Comment (fregante) [inline source/features/unread-anywhere.tsx:101]: It no longer uses generic "grouped buttons" classes like AppHeader-buttonRight or BtnGroup so we have to manage rounded corners manually. 

Also see note in CSS file

File: source/features/unread-anywhere.tsx (hunk 1 above)
Comment (SunsetTechuila) [inline source/features/unread-anywhere.tsx:62]: Should we hide the button itself too?

Image

File: source/features/unread-anywhere.tsx [hunk 4]
```diff
@@ -1,13 +1,14 @@
+import './unread-anywhere.css';
 import React from 'dom-chef';
```
Comment (SunsetTechuila) [inline source/features/unread-anywhere.tsx:3]:
```suggestion
import './unread-anywhere.css';

import React from 'dom-chef';
```

**Review by SunsetTechuila — APPROVED** [review]

File: source/features/unread-anywhere.tsx (hunk 1 above)
Comment (fregante) [reply source/features/unread-anywhere.tsx:62]: The button was intentionally left  behind back then because the UI could show "no notifications" but they actually existed.

_If_ the issue is completely and totally resolved, then we can still leave it behind simply to keep it simple (we'd have to track class removal, handle class restoration, etc). I think hiding the button after a click is a bit "shocking" too, so I'd lean towards leaving it. Easier and less shocking.

File: source/features/unread-anywhere.tsx (hunk 4 above)
Comment (fregante) [reply source/features/unread-anywhere.tsx:3]: We never enabled Biome's import sorting and grouping 🥲

**Comment by fregante** [comment]
by the way do we have a way to achieve this hotkey style?

Screenshot 10
Screenshot 9

**Comment by SunsetTechuila** [comment]
It would be easier to clone the tooltip

**Comment by SunsetTechuila** [comment]
Here is the last version of code I wrote for `rerun-workflow`:

```tsx
function createTooltip(hotkey: string): HTMLElement | void {
	const notificationsTooltip = $optional('a[href="/notifications"]')?.nextElementSibling;
	if (!notificationsTooltip) {
		return;
	}

	const tooltip = notificationsTooltip.cloneNode(true) as HTMLElement;

	const label = tooltip.firstElementChild!;
	label.id = '';
	label.firstChild!.textContent = '';
	label.firstElementChild!.childNodes[2].textContent = hotkey.split(' ').join(' then ');

	const keybindingHint = $('kbd', tooltip);
	for (const hintText of []) {

	}

	return tooltip;
}
```

**Comment by fregante** [comment]
It would be good to create a helper that lets us add new tooltips like that to any element, removing any pre-existing `labelled-by`, `aria-label` and `tooltipped`
