### PR TITLE
`one-click-diff-options` - Restore `d w` shortcut in PRs

### LINKED ISSUE #9232: `one-click-diff-options` broken
(See parent issue)

### PR DESCRIPTION
**Pull request by fregante**
- closes https://github.com/refined-github/refined-github/issues/9232

## Test URLs

Shortcut only:
- PR files: https://github.com/refined-github/refined-github/pull/6261/files
- Single commit: https://github.com/rancher/rancher/commit/e82921075436c21120145927d5a66037661fcf4e

Button:
- Compare, in "Files changed" tab: https://github.com/rancher/rancher/compare/v2.6.3...v2.6.6
- Compare, without tab: https://github.com/rancher/rancher/compare/v2.6.5...v2.6.6

## Tab

Screenshot 15

## No tab

Screenshot 14

## Disable style (unchanged)

Screenshot 16

### CODE REVIEW

**Comment by fregante** [comment]
## New feature screenshot

Screenshot 17

File: source/features/one-click-diff-options.tsx [hunk 1]
```diff
@@ -1,23 +1,16 @@
...
 
 import features from '../feature-manager.js';
-import {removeTextNodeContaining} from '../helpers/dom-utils.js';
 import observe from '../helpers/selector-observer.js';
+import {registerHotkey} from '../github-helpers/hotkey.js';
 
 function isHidingWhitespace(): boolean {
-	// The selector is the native button
-	return new URL(location.href).searchParams.get('w') === '1'
-		|| elementExists('button[name="w"][value="0"]:not([hidden])');
```
Comment (fregante) [inline source/features/one-click-diff-options.tsx:17]: GitHub no longer preserves the setting across loads. If the page doesn't have `?w=1` then whitespace changes are visible.

There's a minor "issue" where if you are on `pull/123/changes?w=1` and click the "Files changed" tab, GitHub will remove the URL parameter. The page is not reloaded, so it doesn't really affect us since `isHidingWhitespace` already ran

File: source/features/one-click-diff-options.tsx [hunk 2]
```diff
@@ -26,97 +19,26 @@ function createWhitespaceButton(): HTMLElement {
...
+			className={'float-right mr-3 tooltipped tooltipped-s btn btn-sm tooltipped ' + (isHidingWhitespace() ? 'color-fg-subtle' : '')}
 			aria-label={`${isHidingWhitespace() ? 'Show' : 'Hide'} whitespace changes`}
 		>
 			{isHidingWhitespace() && <CheckIcon />} No Whitespace
-		</a>
+		</a>,
 	);
 }
 
-function attachPrButtons(dropdown: HTMLDetailsElement): void {
```
Comment (fregante) [inline source/features/one-click-diff-options.tsx:41]: Buttons dropped from PR because the native popup is now fast enough:

Image

Back then it would require an additional click to "save" the options change. Now it doesn't even require a page load for the layout switch.

File: source/features/one-click-diff-options.tsx [hunk 3]
```diff
@@ -26,97 +19,26 @@ function createWhitespaceButton(): HTMLElement {
...
-function initPr(signal: AbortSignal): void {
-	// There are two "diff settings" element, one for mobile and one for the desktop. We only replace the one for the desktop
-	observe('.hide-sm.hide-md details.diffbar-item:has(svg.octicon-gear)', attachPrButtons, {signal});
-}
-
-function attachButtons(nativeDiffButtons: HTMLElement): void {
-	const anchor = nativeDiffButtons.parentElement!;
-
-	// `usesFloats` is necessary to ensure the order and spacing as seen in #5958
-	const usesFloats = anchor?.classList.contains('float-right');
```
Comment (fregante) [inline source/features/one-click-diff-options.tsx:108]: `usesFloats` is now always true, so I dropped the condition

File: source/features/one-click-diff-options.tsx [hunk 4]
```diff
@@ -129,12 +51,12 @@ void features.add(import.meta.url, {
 	shortcuts,
 	include: [
 		pageDetect.isPRFiles,
+		pageDetect.isSingleCommit,
 	],
 	exclude: [
 		pageDetect.isPRFile404,
-		pageDetect.isEnterprise, // #5820
```
Comment (fregante) [inline source/features/one-click-diff-options.tsx:135]: 2022 me: "Can be dropped in 3 months" without leaving a comment 😅

File: source/features/one-click-diff-options.tsx (hunk 2 above)
Comment (SunsetTechuila) [reply source/features/one-click-diff-options.tsx:41]: >  the native popup is now fast enough

As someone who often switches between unified and split views, I disagree

Comment (fregante) [reply source/features/one-click-diff-options.tsx:41]: Keyboard shortcut time?

Comment (SunsetTechuila) [reply source/features/one-click-diff-options.tsx:41]: Here is my unfinished commit that restores the feature: https://github.com/SunsetTechuila/refined-github/commit/21ebe556e8de9ce6076c50dec6cf1695d3f4276f

Comment (fregante) [reply source/features/one-click-diff-options.tsx:41]: That's the problem with having open/unfinished work for months, it blocks others from working on issues

Comment (fregante) [reply source/features/one-click-diff-options.tsx:41]: Since it has substantial changes and we can drop the GHE version, I'd say I can merge this PR (since it does restore `d w`) and then you can take your time restoring the buttons cleanly on the new PR view

Comment (SunsetTechuila) [reply source/features/one-click-diff-options.tsx:41]: OK
