### PR TITLE
Fix deduplication of `list-prs-for-file` feature

### LINKED ISSUE #5233: `list-prs-for-file` appears duplicated when there are multiple PRs
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

1. Open https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts
2. Visit Code tab
3. Go back
4. See multiple widgets

This only happens when there are multiple PRs. It's not happening on https://github.com/refined-github/refined-github/blob/main/source/refined-github.ts currently

https://user-images.githubusercontent.com/1402241/146770495-13ba7afd-b3cd-4d56-a9d8-f36fe586f5ee.mov

### Example URL

https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts

### Browser(s) used

Safari 15.1

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5233 

## Test URLs

https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts

## Screenshot

https://user-images.githubusercontent.com/46634000/147075143-a1472d44-1506-4a75-9f1a-14ed6e4182e2.mp4

### CODE REVIEW

File: source/features/list-prs-for-file.tsx [hunk 1]
```diff
@@ -162,7 +162,7 @@ void features.add(import.meta.url, {
 		pageDetect.isEditingFile,
 		pageDetect.isSingleFile,
 	],
-	deduplicate: '.rgh-list-prs-for-file', // #3945
```
Comment (cheap-glitch) [inline source/features/list-prs-for-file.tsx:165]: The dropdown was missing that class, but the button had it.

**Review by cheap-glitch — COMMENTED** [review]
There are quite a few features using specific classes for deduplication purposes. I think most of those could be replaced by `has-rgh-inner`.

File: source/features/list-prs-for-file.tsx (hunk 1 above)
Comment (fregante) [reply source/features/list-prs-for-file.tsx:165]: Doesn't this reintroduce https://github.com/refined-github/refined-github/issues/3945?
