### PR TITLE
`no-self-reference` - Fix false positives

### LINKED ISSUE #9077: `no-self-reference`: false positive when links reference each other
### Description

https://github.com/user-attachments/assets/7ad8d09a-80a5-4acd-b133-d0703bcca263

when navigating `issue A` to referenced `issue B` and `issue B` references `issue A`, it falsely warns that link to `issue B` in `issue A` is a self-reference.
reloading the page with F5 fixes it.
possibly due to stale URL after [turbo](https://turbo.hotwired.dev) page replacement

### How to replicate the issue + URL

1. go to https://github.com/expressjs/express/issues/5462
2. navigate to https://github.com/expressjs/express/issues/6863 by clicking referenced links

### Extension version

26.3.3

### Browser(s) used

firefox 149.0b6 (aarch64)

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
Fixes #9077

## Test URLs

https://github.com/expressjs/express/issues/5462 -> https://github.com/expressjs/express/issues/6863

### CODE REVIEW

**Comment by fregante** [comment]
I don't mind the tests from the other PR, can you make that PR mergeable instead? You can add a co-author. 

Having the tests here might let us iterate and document the logic better later.

**Comment by fregante** [comment]
The PR is mergeable. I'll let you merge it with co-author

**Comment by SunsetTechuila** [comment]
I don't like the other PR and don't feel like arguing whether the tests in it are useful

**Comment by SunsetTechuila** [comment]
image

File: source/features/no-self-reference.tsx [hunk 1]
```diff
@@ -17,8 +26,7 @@ function underlineSelfReference(link: HTMLElement): void {
 }
 
 function init(signal: AbortSignal): void {
-	const [currentPage] = location.href.split('#');
-	observe(`.markdown-body:is(:not(section[aria-label="Events"] *)) .issue-link[href="${currentPage}"]`, underlineSelfReference, {signal});
+	observe('.markdown-body:is(:not(section[aria-label="Events"] *)) a.issue-link', underlineSelfReference, {signal});
```
Comment (fregante) [inline source/features/no-self-reference.tsx]: Why not use the selector as suggested? Would be shorter

Also I don’t think :is() is needed here

Comment (SunsetTechuila) [reply source/features/no-self-reference.tsx]: > Why not use the selector as suggested?

1. It's easier to comment on a specific check that way
2. Having checks in one place makes the logic easier to follow
3. It's _probably_ _slightly_ more efficient

Comment (fregante) [reply source/features/no-self-reference.tsx]: 1. Comments are possible either way, we have many such examples
2. So why not also drop the other :not() in this selector? The logic is already split
3. We're probably talking about micro-optimizations here, but my guess is that "selector matching" is more efficient than "selector matching + animation start + JS listener call" only to be cancelled later. 

"Logic in callbacks" is only generally preferred when the alternative is perf-killing selectors, namely `:has()` on big items.
