### PR TITLE
Restore `show-names` feature

### LINKED ISSUE #5927: `show-names` is broken
### Description

Names aren't shown anywhere anymore
Screen Shot

### How to replicate the issue

- https://github.com/
- This issue

### Extension version

21.8.1, 21.8.8

### Browser(s) used

Safari, Chrome

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5927 

## Test URLs

- This page
- Your newsfeed

## Screenshot

**Conversation**

image

**Newsfeed**

image

### CODE REVIEW

File: source/features/show-names.tsx [hunk 1]
```diff
@@ -84,7 +84,6 @@ void features.add(import.meta.url, {
 	include: [
 		pageDetect.hasComments,
 	],
-	onlyAdditionalListeners: true,
```
Comment (cheap-glitch) [inline source/features/show-names.tsx:87]: The feature was inadvertently disabled by #5873 (https://github.com/refined-github/refined-github/pull/5873/files#diff-bb287cee7084ff807d23e0ac0cdee19825f4c215ce976f3ab5f608448c4bc8eaR87)

File: source/github-events/on-newsfeed-load.ts [hunk 2]
```diff
@@ -1,17 +1,17 @@
...
-	// Start from the main container
-	observer.observe(select('.news')!, {childList: true});
+	callback(event);
+}
+
+export default function onNewsfeedLoad(callback: EventListener, signal: AbortSignal): void {
+	createFragmentLoadListener('.news include-fragment[src="/dashboard-feed"]', event => {
+		onNewsfeedPageLoad(event, callback, signal);
+	}, signal);
 }
```
Comment (cheap-glitch) [inline source/github-events/on-newsfeed-load.ts:17]: Rewrote the broken `onNewsfeedLoad` listener (only used by `show-names`) to use GitHub events instead of a `MutationObserver`.

Comment (fregante) [reply source/github-events/on-newsfeed-load.ts:17]: Was this broken too?

We should use the new selector observer wherever possible and move away from other listeners, especially when nested like this one.

But if this already fixes an issue and it works, it's fine

Comment (cheap-glitch) [reply source/github-events/on-newsfeed-load.ts:17]: > Was this broken too?

Yes, since GitHub changed the DOM a lot when introducing the "For you" tab, and now there's a lot more nested elements that are progressively loaded and don't have very specific classes/attributes to target.

This could also have been fixed by adding `subtree: true` to the listener, but listening to events and running the feature only when needed is probably a lot more efficient.

Comment (fregante) [reply source/github-events/on-newsfeed-load.ts:17]: > This could also have been fixed by adding `subtree: true` to the listener

See #5886. We don't have to think about that anymore 🎉 

The new observer is not strictly equivalent however, for example the elements must be "not hidden" or else the observer can't see them.

**Review by fregante — APPROVED** [review]
It'd be great to see the new observer instead, but merge at will.

**Comment by cheap-glitch** [comment]
I merged it for now, will open a meta PR when I have a bit more time.

This will be a good way of getting my feet wet with the new observer :slightly_smiling_face:

**Comment by fregante** [comment]
> It'd be great to see the new observer instead, but merge at will.

Done in https://github.com/refined-github/refined-github/pull/5991
