### PR TITLE
Less flashy `closing-remarks`

### LINKED ISSUE #6482: `closing-remarks` has wrong style
### Description

Icon has unnecessary margin

image

### How to replicate the issue + URL

https://github.com//refined-github/refined-github/pull/6427#ref-pullrequest-1640816674

### Extension version

23.3.31

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #6482 
- Addresses https://github.com/refined-github/refined-github/issues/5851#issuecomment-1195289714
- May replace #6489 

## Test URLs

- PR: https://github.com/refined-github/refined-github/pull/5600
- Locked PR: https://github.com/eslint/eslint/pull/17
- Archived repo: https://github.com/fregante/iphone-inline-video/pull/130
- RGH tagged PR: https://github.com/refined-github/sandbox/pull/1

## Released

Screenshot 9

## Unreleased

Screenshot 8

### CODE REVIEW

File: source/features/closing-remarks.tsx [hunk 1]
```diff
@@ -29,14 +29,26 @@ const getFirstTag = cache.function('first-tag', async (commit: string): Promise<
...
+
 async function init(): Promise<void> {
 	const mergeCommit = select(`.TimelineItem.js-details-container.Details a[href^="/${getRepo()!.nameWithOwner}/commit/" i] > code`)!.textContent!;
 	const tagName = await getFirstTag(mergeCommit);
 
 	if (tagName) {
 		addExistingTagLink(tagName);
 	} else {
-		void addReleaseBanner('The merge commit doesn’t appear in any tags');
+		void addReleaseBanner('This PR’s merge commit doesn’t appear in any tags');
```
Comment (fregante) [inline source/features/closing-remarks.tsx:51]: The copy was a little too vague

File: source/features/closing-remarks.tsx [hunk 2]
```diff
@@ -61,14 +73,14 @@ function addExistingTagLink(tagName: string): void {
...
 
+	const linkedTag = <a href={tagUrl} className="text-mono text-small">{tagName}</a>;
 	attachElement('#issue-comment-box', {
 		before: () => (
 			<TimelineItem>
 				{createBanner({
-					text: <>This pull request first appeared in <span className="text-mono text-small">{tagName}</span></>,
-					classes: ['flash-success'],
-					action: tagUrl,
-					buttonLabel: <><TagIcon/> See release</>,
```
Comment (fregante) [inline source/features/closing-remarks.tsx:71]: This widget only shows the _state_ of the PR, it doesn't require any actions, so I think it'd make sense to _not_ use the button.

This now also helps differentiate the two states:

- released
- unreleased

… because they used to be clearly blue and clearly green, but now their color varies very little.

File: source/features/closing-remarks.tsx [hunk 3]
```diff
@@ -80,19 +92,21 @@ async function addReleaseBanner(text = 'Now you can release this change'): Promi
...
 		before: () => (
 			<TimelineItem>
 				{createBanner(url ? {
-					text,
+					...bannerContent,
 					action: url,
-					buttonLabel: <><TagIcon/> Draft a new release</>,
-				} : {text})}
+					buttonLabel: 'Draft a new release',
+				} : bannerContent)}
```
Comment (fregante) [inline source/features/closing-remarks.tsx:109]: `RequireAllOrNone` types make optional properties annoying to use. Feel free to try locally

File: source/features/closing-remarks.tsx [hunk 4]
```diff
@@ -80,19 +92,21 @@ async function addReleaseBanner(text = 'Now you can release this change'): Promi
...
 	attachElement('#issue-comment-box', {
 		before: () => (
 			<TimelineItem>
 				{createBanner(url ? {
-					text,
+					...bannerContent,
 					action: url,
-					buttonLabel: <><TagIcon/> Draft a new release</>,
-				} : {text})}
+					buttonLabel: 'Draft a new release',
```
Comment (fregante) [inline source/features/closing-remarks.tsx:108]: - Icon gone, fixes #6482

File: source/features/closing-remarks.tsx [hunk 5]
```diff
@@ -61,14 +73,14 @@ function addExistingTagLink(tagName: string): void {
...
+	const linkedTag = <a href={tagUrl} className="text-mono text-small">{tagName}</a>;
 	attachElement('#issue-comment-box', {
 		before: () => (
 			<TimelineItem>
 				{createBanner({
-					text: <>This pull request first appeared in <span className="text-mono text-small">{tagName}</span></>,
-					classes: ['flash-success'],
-					action: tagUrl,
-					buttonLabel: <><TagIcon/> See release</>,
+					icon: <TagIcon className="m-0"/>,
```
Comment (fregante) [inline source/features/closing-remarks.tsx:81]: The tag also aligns it well with `rgh-netiquette` in https://github.com/refined-github/sandbox/pull/1

Screenshot 11

File: source/features/closing-remarks.tsx [hunk 6]
```diff
@@ -61,14 +73,14 @@ function addExistingTagLink(tagName: string): void {
 		);
 	}
 
+	const linkedTag = <a href={tagUrl} className="text-mono text-small">{tagName}</a>;
```
Comment (kidonng) [inline source/features/closing-remarks.tsx:76]: Not enough attention?

```suggestion
	const linkedTag = <a href={tagUrl} className="Link--primary text-bold">{tagName}</a>;
```

image

**Comment by kidonng** [comment]
This is a good chance to refactor `createBanner` a bit:

https://github.com/refined-github/refined-github/blob/bac8aec98b453861985d0d8add4cf474e417c756/source/github-helpers/banner.tsx#L12-L13

```diff
- // Classes copied from "had recent pushes" banner from repo home
+ // https://primer.style/css/components/alerts#with-action-button
const classes = 'btn btn-sm flash-action';
```

https://github.com/refined-github/refined-github/blob/bac8aec98b453861985d0d8add4cf474e417c756/source/github-helpers/banner.tsx#L35-L44

```diff
<div className={['flash', ...props.classes ?? ''].join(' ')}>
-	<div className="d-sm-flex flex-items-center gap-2">
-		<div className="d-flex flex-auto flex-self-center flex-items-center gap-2">
			{props.icon}
			{/* TODO: Drop `any` after https://github.com/frenic/csstype/issues/177 */}
			<span style={{textWrap: 'balance'} as any}>{props.text}</span>
-		</div>
		{button}
-	</div>
</div>
```

This was intended to be part of #6489

**Comment by fregante** [comment]
As the inline comment suggests, we're using GitHub’s own classes. I'm pretty sure that they lead to a better result than just that. See the current mobile version:

Screenshot 17

versus what I get (if I didn't make mistakes) by applying your change:

Screenshot 18

**Comment by fregante** [comment]
Indeed 🙂 

Screenshot 19

**Comment by kidonng** [comment]
That's float for you!

It doesn't make sense to revert that PR. I will just create a new one to get rid of `flash` completely.

**Review by kidonng — APPROVED** [review]

**Comment by fregante** [comment]
> I will just create a new one to get rid of `flash` completely.

Reasoning?

**Comment by kidonng** [comment]
> Reasoning?

Because we are overriding most things from that class?

**Comment by fregante** [comment]
> > Reasoning?
> 
> Because we are overriding most things from that class?

We're not? Borders, rounding, spacing, colors, icon colors still come from `flash`. None of those classes actually override anything, we're only overriding the `background` right?

**Comment by fregante** [comment]
It looks like GitHub uses the same format and location to display status in open PRs:

Screenshot 9

The HTML

```html
<div
  class="border color-border-default rounded-2 branch-action-item js-details-container js-transitionable"
>
  <!-- We could pass view here, but since this partial is rendered directly by a controller action,
           it's easiest to just always pass a pull and have the view initialize the view -->

  <div
    class="merge-status-list-wrapper"
  >
    <div
      class="float-left branch-action-item-icon completeness-indicator circle color-fg-muted border"
    >
      <svg
        aria-hidden="true"
        height="16"
        viewBox="0 0 16 16"
        version="1.1"
        width="16"
        data-view-component="true"
        class="octicon octicon-rocket"
      >
        <path
          d="M14.064 0h.186C15.216 0 16 .784 16 1.75v.186a8.752 8.752 0 0 1-2.564 6.186l-.458.459c-.314.314-.641.616-.979.904v3.207c0 .608-.315 1.172-.833 1.49l-2.774 1.707a.749.749 0 0 1-1.11-.418l-.954-3.102a1.214 1.214 0 0 1-.145-.125L3.754 9.816a1.218 1.218 0 0 1-.124-.145L.528 8.717a.749.749 0 0 1-.418-1.11l1.71-2.774A1.748 1.748 0 0 1 3.31 4h3.204c.288-.338.59-.665.904-.979l.459-.458A8.749 8.749 0 0 1 14.064 0ZM8.938 3.623h-.002l-.458.458c-.76.76-1.437 1.598-2.02 2.5l-1.5 2.317 2.143 2.143 2.317-1.5c.902-.583 1.74-1.26 2.499-2.02l.459-.458a7.25 7.25 0 0 0 2.123-5.127V1.75a.25.25 0 0 0-.25-.25h-.186a7.249 7.249 0 0 0-5.125 2.123ZM3.56 14.56c-.732.732-2.334 1.045-3.005 1.148a.234.234 0 0 1-.201-.064.234.234 0 0 1-.064-.201c.103-.671.416-2.273 1.15-3.003a1.502 1.502 0 1 1 2.12 2.12Zm6.94-3.935c-.088.06-.177.118-.266.175l-2.35 1.521.548 1.783 1.949-1.2a.25.25 0 0 0 .119-.213ZM3.678 8.116 5.2 5.766c.058-.09.117-.178.176-.266H3.309a.25.25 0 0 0-.213.119l-1.2 1.95ZM12 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"
        ></path>
      </svg>
    </div>

    <h3 class="h4 status-heading">This branch has not been deployed</h3>
    <span class="status-meta"> No deployments </span>
  </div>
</div>
```
