### PR TITLE
`vertical-front-matter` - Restore feature

### LINKED ISSUE #8650: `vertical-front-matter` does not work due to the selector no longer matching the front matter table
### Description

GitHub seems to render markdown tables (or at least the front matter table) wrapped in a `<markdown-accessiblity-table>...</markdown-accessiblity-table>` element.

https://github.com/refined-github/refined-github/blob/4f2fd4010b0a6abddf147cae688eed810e9061ad/source/features/vertical-front-matter.tsx#L35-L37

Updating the selector to account for this element fixed the issue for me:

```diff
function init(signal: AbortSignal): void {
-	observe('.markdown-body > table:first-child', transpose, {signal});
+	observe(['.markdown-body > table:first-child', '.markdown-body > markdown-accessiblity-table > table:first-child'], transpose, {signal});
}
```

### How to replicate the issue + URL

Test URL from `vertical-front-matter` source code: https://github.com/github/docs/blob/114de99a/content/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github.md

### Extension version

25.8.27

### Browser(s) used

Firefox 142.0 on Linux

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by Bahex**
Closes #8650

## Test URLs
- https://github.com/github/docs/blob/114de99a/content/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github.md

### CODE REVIEW

**Review by kovsu — APPROVED** [review]

File: source/features/vertical-front-matter.tsx [hunk 1]
```diff
@@ -33,7 +33,14 @@ function transpose(table: HTMLElement): void {
 }
 
 function init(signal: AbortSignal): void {
-	observe('.markdown-body > table:first-child', transpose, {signal});
+	observe(
+		[
+			'.markdown-body > table:first-child', // TODO: remove in march 2026
+			'.markdown-body > markdown-accessiblity-table > table:first-child',
```
Comment (fregante) [inline source/features/vertical-front-matter.tsx:39]: Is this their misspelling? Accessibility lacks an I

Comment (Bahex) [reply source/features/vertical-front-matter.tsx:39]: Their misspelling. I can add an additional correctly spelled selector to future proof it.
