### PR TITLE
Fix `hide-own-stars`

### LINKED ISSUE #6192: `hide-own-stars` is a bit broken
### Native 

Screen Shot 1

### RG

The single events are hidden, but the group isn't

gif23

### How to replicate the issue + URL

1. https://github.com
2. Look for people starring your own repos

### Extension version

22.11.21

### Browser(s) used

Safari, Chrome

### Related

- #6188

### PR DESCRIPTION
**Pull request by fregante**
- Fix #6192 

## Test URLs

https://github.com/

## Before

Screen Shot 3

## After

 
Screen Shot 4

### CODE REVIEW

File: source/features/hide-own-stars.tsx [hunk 1]
```diff
@@ -1,27 +1,22 @@
...
-			.fork
-		)
-	`, hide, {signal});
+	const own = `:has(a[href^="/${getUsername()!}"])`;
+	observe([
+		// Single events
+		`#dashboard :is(.watch_started, .fork)${own}`,
+
+		// Grouped events
+		`#dashboard .body:has(.watch_started, .fork)${own}`,
```
Comment (fregante) [inline source/features/hide-own-stars.tsx:18]: Yes, :has(), no other way

#5797
