### PR TITLE
`status-subscription` - Fix when opening issue in new tab in Firefox

### LINKED ISSUE #9057: `status-subscription` does not work when opening issue in a new tab
### Description

The 3 subscribe buttons do not appear when opening pages in a new tab and switching after its fully loaded.

Image

Error in the console: `ElementNotFoundError: Expected element not found: meta[name="release"]`

### How to replicate the issue + URL

Open any issue or PR in a new tab, wait for it to load, notice the `status-subscription` feature doesnt apply.

### Extension version

26.3.3

### Browser(s) used

Firefox

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
Fixes #9057 

Don't ask me why this was only failing in Firefox

## Test URLs

https://github.com/refined-github/refined-github/issues -> open any issue in a new tab

### CODE REVIEW

File: source/features/status-subscription.tsx [hunk 1]
```diff
@@ -112,7 +112,7 @@ function addButton(subscriptionButton: HTMLButtonElement): void {
 const githubApiBaseHeaders = new Headers({
 	accept: 'application/json',
 	'github-verified-fetch': 'true',
-	'x-github-client-version': $('meta[name="release"]').content,
+	'x-github-client-version': 'Refined GitHub. Please address https://github.com/orgs/community/discussions/132506#discussioncomment-11294985',
```
Comment (SunsetTechuila) [inline source/features/status-subscription.tsx:115]: https://github.com/refined-github/refined-github/pull/8790#discussion_r2580057725

**Comment by waldyrious** [comment]
Thank you @SunsetTechuila, for this fix and all your recent work in Refined GitHub! 🥹❤️
