### PR TITLE
Fix position and duplication of `quick-comment-edit` button

### LINKED ISSUE #5558: `quick-comment-edit` is misaligned
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/sindresorhus/serialize-error/pull/69

### Extension version

22.2.13

### Browser(s) used

Safari 15.4

### Description

I'm still on an old version so I'm not sure if it has been fixed in the meanwhile, but I doubt it since it appeared today.

Screen Shot 7

Strangely it's broken in the example PR, but not in the current issue:
Screen Shot

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### LINKED ISSUE #5572: Multiple edit buttons due to `quick-comment-edit`
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/TauCetiStation/TauCetiClassic/pull/7772

### Extension version

22.4.1

### Browser(s) used

Yandex.Browser

### Description

Sometimes, this happens

This is mostly inconsistent, but try to reload the example url multiple times and press the "Load more" button

Console:

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5558 
Fixes #5572 

## Test URLs

Add, edit and delete regular & review comments in conversations

- [Issue conversation](https://togithub.com/refined-github/sandbox/issues/3)
- [PR conversation](https://togithub.com/refined-github/sandbox/pull/10)

## Screenshot

quick-comment-edit

### CODE REVIEW

File: source/features/quick-comment-edit.tsx [hunk 1]
```diff
@@ -7,6 +7,33 @@ import * as pageDetect from 'github-url-detection';
...
+			type="button"
+			role="menuitem"
+			className={`timeline-comment-action btn-link js-comment-edit-button ${pageDetect.isDiscussion() ? 'js-discussions-comment-edit-button' : ''} rgh-quick-comment-edit-button`}
+			aria-label="Edit comment"
+		>
+			<PencilIcon/>
+		</button>
+	);
+
+	const dropdown = comment.querySelector('.timeline-comment-actions > details:last-child')!;
```
Comment (cheap-glitch) [inline source/features/quick-comment-edit.tsx:29]: Need a child combinator in the selector, because the reaction picker on PR comments is also a `<details>`. (GitHub rolled some new reaction pickers, but on in PR conversations only :roll_eyes:)

File: source/features/quick-comment-edit.tsx [hunk 2]
```diff
@@ -7,6 +7,33 @@ import * as pageDetect from 'github-url-detection';
...
+	if (pageDetect.isIssue()) {
+		dropdown.previousSibling!.replaceWith(button); // Replace whitespace node in issue comments header
```
Comment (cheap-glitch) [inline source/features/quick-comment-edit.tsx:31]: image

This might be too brittle to be worth it. Alternatively we could remove the left margin on the edit button.

File: source/features/quick-comment-edit.tsx [hunk 3]
```diff
@@ -7,6 +7,33 @@ import * as pageDetect from 'github-url-detection';
 import features from '.';
 import isArchivedRepo from '../helpers/is-archived-repo';
 
+function addQuickEditButton(commentForm: Element): void {
+	commentForm.classList.add('rgh-edit-comment');
+
+	const comment = commentForm.closest('.js-comment')!;
+	if (select.exists('.rgh-quick-comment-edit-button', comment)) { // #5572
```
Comment (fregante) [inline source/features/quick-comment-edit.tsx:14]: But we already have a deduplication code: `.js-comment-update:not(.rgh-edit-comment)`

If that doesn't work, either we move the class higher in the tree or we drop it

File: source/features/quick-comment-edit.tsx (hunk 2 above)
Comment (fregante) [reply source/features/quick-comment-edit.tsx:31]: Oh yeah they only need to remove one space and this line ends up removing the reaction picker.

> Alternatively we could remove the left margin on the edit button

This

File: source/features/quick-comment-edit.tsx [hunk 4]
```diff
@@ -7,6 +7,33 @@ import * as pageDetect from 'github-url-detection';
 import features from '.';
 import isArchivedRepo from '../helpers/is-archived-repo';
 
+function addQuickEditButton(commentForm: Element): void {
+	const commentBody = commentForm.closest('.js-comment')!;
+	// We can't rely on a class for deduplication because the whole comment might be replaced by GitHub #5572
```
Comment (fregante) [inline source/features/quick-comment-edit.tsx:12]: Hopefully with native :has() we'll be able to do that

**Review by fregante — APPROVED** [review]
