### PR TITLE
`esc-to-deselect-line` - Restore feature

### LINKED ISSUE #7756: `esc-to-deselect-line` broken
### Description

See below

### How to replicate the issue + URL

1. Visit https://github.com/refined-github/refined-github/blob/132272786fdc058193e089d8c06f2a158844e101/source/features/esc-to-deselect-line.tsx#L11
2. Press Esc
3. Selected line does not become deselected

### Extension version

24.8.20

### Browser(s) used

Safari

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by kidonng**
Fix #7756

Related GitHub source code:

```tsx
// Simplified for demonstration
// https://github.githubassets.com/assets/app/assets/modules/react-code-view/components/blob/BlobContent/Code/LineNumber.tsx

<div onMouseDown={preventClick ? undefined : codeCellClickFunc} />

const codeCellClickFunc = event => {
      const targetedLineNumber = parseInt(event.currentTarget.getAttribute('data-line-number')!, 10)
}
```

## Test URLs

https://github.com/refined-github/refined-github/blob/main/source/features/esc-to-deselect-line.tsx

## Screenshot

https://github.com/user-attachments/assets/eb900534-02a7-49d1-9697-89fd21ed22e6

### CODE REVIEW

File: source/features/esc-to-deselect-line.tsx [hunk 1]
```diff
@@ -13,7 +14,22 @@ function isLineSelected(): boolean {
...
+			const {lineNumber} = selectedLineNumber.dataset;
+			selectedLineNumber.dataset.lineNumber = '';
+			// Trigger click to deselect
+			selectedLineNumber.dispatchEvent(new MouseEvent('mousedown', {bubbles: true}));
+			// Restore line number
+			selectedLineNumber.dataset.lineNumber = lineNumber;
+			// Un-focus code block
+			(document.activeElement as HTMLElement).blur();
+		} else {
+			location.hash = '#no-line'; // Update UI, without `scroll-to-top` behavior
```
Comment (fregante) [inline source/features/esc-to-deselect-line.tsx:30]:
```suggestion
			// TODO: Review in December 2025 if old UI is gone. Currently only applies to PRs
			location.hash = '#no-line'; // Update UI, without `scroll-to-top` behavior
```

**Review by fregante — APPROVED** [review]
Fantastic! I thought this wasn't going to be possible
