### PR TITLE
`repo-avatars` - Various fixes

### LINKED ISSUE #8968: `repo-avatars` misaligns breadcrumbs, appends avatar to their overflow menu multiple times
### Description

Image

Image

Image

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

26.2.2

### Browser(s) used

Microsoft Edge 145.0.3800.47 (Official build) beta (64-bit)

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
fixes #8968

addresses https://github.com/refined-github/refined-github/issues/8947#issuecomment-3850845375

## Test URLs

https://github.com/refined-github/refined-github

## Screenshot

image

image

### CODE REVIEW

File: source/features/repo-avatars.tsx [hunk 1]
```diff
@@ -5,41 +5,50 @@ import features from '../feature-manager.js';
...
 	);
 
-	ownerLabel.classList.add('d-flex', 'flex-items-center');
+	const container = isOldNavbar ? ownerLabel : ownerLabel.parentElement!;
+	container.classList.add('d-flex', 'flex-items-center');
+
 	ownerLabel.prepend(avatar);
 
-	if (!ownerLabel.closest('[data-hovercard-type="organization"]')) {
+	if (!pageDetect.isOrganizationRepo()) {
```
Comment (SunsetTechuila) [inline source/features/repo-avatars.tsx:32]: broken

Comment (SunsetTechuila) [reply source/features/repo-avatars.tsx:32]: https://github.com/refined-github/github-url-detection/pull/231

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Can be merged after you install the URL detection update (after that PR is merged)

**Comment by SunsetTechuila** [comment]
> Can be merged after you install the URL detection update

That would also affect `user-profile-follower-badge` - #8952

Shouldn't this be a separate PR?

**Comment by fregante** [comment]
Ok then. But merge that one before this one since this PR as is does not fix the feature (from what I understand)

**Comment by SunsetTechuila** [comment]
> this PR as is does not fix the feature (from what I understand)

https://github.com/refined-github/github-url-detection/pull/230 fixed https://github.com/refined-github/refined-github/issues/8952

image

**Comment by fregante** [comment]
Does this PR fix https://github.com/refined-github/refined-github/issues/8968 without updating the package?

**Comment by SunsetTechuila** [comment]
Yes, updating `github-url-detection` will only make organization avatars non-circular

**Comment by fregante** [comment]
What does this comment mean? It's broken or not? https://github.com/refined-github/refined-github/pull/8971#discussion_r2794413552

**Comment by SunsetTechuila** [comment]
`isOrganizationRepo` is broken but this feature uses it only to decide the avatar shape
