### PR TITLE
Restore `infinite-scroll` broken on new dashboard

### LINKED ISSUE #6912: `infinite-scroll` broken on new dashboard
### Description

image

```console
Uncaught TypeError: Cannot read properties of undefined (reading 'click') at debounce_fn.wait
````

### How to replicate the issue + URL

Visit https://github.com/ or https://github.com/dashboard.

Scroll down to the end of the Dashboard feed until you see the "More" button. Then the error shows in the console.

### Extension version

23.9.7

### Browser(s) used

Edge Stable

### PR DESCRIPTION
**Pull request by 134130**
## Description
- Closes #6912

## Changes
- The main reason of the issue is `select('[role="tabpanel"]:not([hidden]) button.ajax-pagination-btn')!` is no longer available
  - Fix the selector.
- Remove deprecated `deduplicate: 'has-rgh'` and `awaitDomReady: true` with using `selector-observer`

## Test URLs
- https://github.com/

## Screenshot
image

### CODE REVIEW

File: source/features/infinite-scroll.tsx [hunk 1]
```diff
@@ -7,35 +7,28 @@ import features from '../feature-manager.js';
 import observe from '../helpers/selector-observer.js';
 import onAbort from '../helpers/abort-controller.js';
 
-const loadMore = debounce(() => {
-	const button = select('[role="tabpanel"]:not([hidden]) button.ajax-pagination-btn')!;
+const loadMore = debounce((button: HTMLButtonElement) => {
 	button.click();
-	button.textContent = 'Loading…';
```
Comment (134130) [inline source/features/infinite-scroll.tsx:13]: Drop editing textContent since GitHub is already changes its textContent to `Loading more...`

**Review by fregante — APPROVED** [review]
Untested but LGTM
