### PR TITLE
`pr-jump-to-first-non-viewed-file` - Restore feature in all PRs

### LINKED ISSUE #7030: `pr-jump-to-first-non-viewed-file`: broken in some cases
### Description

It seems to work on https://github.com/refined-github/sandbox/pull/55/files

But not on https://togithub.com/pixiebrix/pixiebrix-extension/pull/6808/files

https://github.com/refined-github/refined-github/assets/1402241/52344afa-96a1-459a-9cc4-d625077ca96e

### Extension version

23.9.21

### Browser(s) used

Safari

### PR DESCRIPTION
**Pull request by DerTimonius**
## Description
This PR fixes the issue with the `pr-jump-to-first-non-viewed-file` feature by adapting the selector and tighten the check a bit by not only checking against the `firstNonViewedFile` value but also its `id`.
Fixes #7030

## Test URLs
https://github.com/pixiebrix/pixiebrix-extension/pull/6808/files

### CODE REVIEW

File: source/features/pr-jump-to-first-non-viewed-file.tsx [hunk 1]
```diff
@@ -6,8 +6,8 @@ import * as pageDetect from 'github-url-detection';
 import features from '../feature-manager.js';
 
 function jumpToFirstNonViewed(): void {
-	const firstNonViewedFile = $('.file:not([data-file-user-viewed])')!;
-	if (firstNonViewedFile) {
+	const firstNonViewedFile = $('.file[data-details-container-group="file"]:not([data-file-user-viewed])')!;
```
Comment (DerTimonius) [inline source/features/pr-jump-to-first-non-viewed-file.tsx:9]: Adding this selector prevents selecting the wrong DOM element (maybe the classes in changed in the past)

File: source/features/pr-jump-to-first-non-viewed-file.tsx [hunk 2]
```diff
@@ -6,8 +6,8 @@ import * as pageDetect from 'github-url-detection';
...
+	if (firstNonViewedFile && firstNonViewedFile.id) {
```
Comment (DerTimonius) [inline source/features/pr-jump-to-first-non-viewed-file.tsx:10]: Issue occurred because a file was found, but it had no `id`

**Review by fregante — APPROVED** [review]
☺️
