### PR TITLE
`conversation-links-on-repo-lists` - Restore on global search

### LINKED ISSUE #7174: `conversation-links-on-repo-lists` missing on global search
### Description

Feature not working on global search, probably broke when GitHub updated the search UI.

image

### How to replicate the issue + URL

https://github.com/search?q=user%3Afregante&type=repositories

### Extension version

23.12.17

### Browser(s) used

Google Chrome

### PR DESCRIPTION
**Pull request by Katsute**
Fixes #7174

## Test URLs

https://github.com/search?q=user%3Afregante&type=repositories

## Screenshot

image

### CODE REVIEW

File: source/features/conversation-links-on-repo-lists.tsx [hunk 1]
```diff
@@ -34,20 +34,48 @@ function addConversationLinks(repositoryLink: HTMLAnchorElement): void {
...
 
-const selectors = [
-	'a[itemprop="name codeRepository"]', // `isProfileRepoList`
-	'.repo-list-item .f4 a', // `isGlobalSearchResults`
-] as const;
+function addSearchConversationLinks(repositoryLink: HTMLAnchorElement): void {
+	const repository = repositoryLink.closest('[data-testid="results-list"] > div')!;
+
+	// Place before the update date ·
+	$('ul > span:last-of-type', repository)!.before(
```
Comment (fregante) [inline source/features/conversation-links-on-repo-lists.tsx:41]: You can use this format instead of a new constant and $()
```suggestion
	repositoryLink
     .closest(blah blah)
     .querySelector('ul > span:last-of-type', repository)!
     .before(
```

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
The spacing is a bit off, I think we need a single dot before the first icon

**Comment by Katsute** [comment]
image

**Comment by Katsute** [comment]
not sure why the linter is failing, indentation looks correct. `xo --fix` messes up the indentation and doesn't pass the linter

**Comment by fregante** [comment]
> not sure why the linter is failing, indentation looks correct. `xo --fix` messes up the indentation and doesn't pass the linter

People insist that _eslint is good enough for formatting_ but dismiss these bugs. I'm not ready to switch to Prettier on this repo yet, but this is what we have to deal with
