### PR TITLE
Fix: `dim-bots` only works on the first page

### LINKED ISSUE #5260: `dim-bots` only works on the first page
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/renovatebot/renovate/commits/main

### Browser(s) used

Chrome

### Description

https://user-images.githubusercontent.com/44045911/147964542-d8474d4e-8fb1-476c-8f19-432c1d6b95e4.mov

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5260

## Test URLs

Go to https://github.com/renovatebot/renovate/commits/main and click on "Older" at the bottom of the page

## Screenshot

https://user-images.githubusercontent.com/46634000/148674527-0f7e5650-b2a4-4860-a7c6-c8f29c2dbb86.mp4

### CODE REVIEW

File: source/features/dim-bots.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ function init(): void {
 
 	// Delay collapsing, but only after they're collapsed on load #5158
 	requestAnimationFrame(() => {
-		document.documentElement.classList.add('rgh-dim-bots--after-hover');
+		select('#repo-content-pjax-container .js-navigation-container')!.classList.add('rgh-dim-bots--after-hover');
```
Comment (kidonng) [inline source/features/dim-bots.tsx:43]: Let PJAX replaces the container with class instead of us doing the chore.

Note only using `#repo-content-pjax-container` does not work since the PJAX container is not replaced sometimes (e.g. switching tabs).

**Review by fregante — APPROVED** [review]

**Comment by kidonng** [comment]
@fregante I managed to restored dimming while avoid ["adding a whole other block to add this intermediary state"](https://github.com/refined-github/refined-github/pull/5198#issuecomment-993381037):

https://user-images.githubusercontent.com/44045911/148685609-08232449-f5d8-4ad2-baff-031de031adfd.mov

What do you think about it?

File: source/features/dim-bots.css [hunk 2]
```diff
@@ -3,24 +3,20 @@ READ BEFORE EDITING. Some selectors match the same items ("focused" selector vs
 Commits that have a long commit message will not be dimmed after the user uncollapses the `<details>` element.
 */
 
-:root {
-	--rgh-dim-bots-delay: 0s;
-}
-
 .rgh-dim-bots--after-hover {
-	--rgh-dim-bots-delay: 60s; /* #5158 */
+	--rgh-dim-bots-delay: 10s; /* #5158 */
```
Comment (kidonng) [inline source/features/dim-bots.css:7]: Would like to see the bots are eventually folded, 10s should keeps the best of both worlds.

Comment (cheap-glitch) [reply source/features/dim-bots.css:7]: I agree that 60 seconds is too long, but this should be moved to a separate PR tagged with `change request`, since it has nothing to do with the bugfix.

Comment (kidonng) [reply source/features/dim-bots.css]: Moved to #5285
