### PR TITLE
Fix `pull-request-hotkey` feature

### LINKED ISSUE #5453: `pull-request-hotkey` is broken
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/1167

### Extension version

22.2.13

### Browser(s) used

Safari 15.3

### Description

1. Open any PR
2. Press `g` `1`
3. Nothing happens

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5453 

## Test URLs

https://togithub.com/refined-github/sandbox/pull/4

## Screenshot

https://user-images.githubusercontent.com/46634000/157320748-fe1b396e-3a66-4c3c-82f3-09fbadf4f130.mp4

### CODE REVIEW

File: source/features/pull-request-hotkey.tsx [hunk 1]
```diff
@@ -4,19 +4,20 @@ import * as pageDetect from 'github-url-detection';
...
 		const keys = [`g ${index + 1}`];
+
 		if (index === selectedIndex - 1 || (selectedIndex === 0 && index === lastTab)) {
 			keys.push('g ArrowLeft');
 		} else if (index === selectedIndex + 1 || (selectedIndex === lastTab && index === 0)) {
 			keys.push('g ArrowRight');
 		}
 
-		tab.dataset.hotkey = String(keys);
+		tab.dataset.hotkey = keys.join(',');
```
Comment (cheap-glitch) [inline source/features/pull-request-hotkey.tsx:20]: Unnecessarily tricky code (imo)

File: source/features/pull-request-hotkey.tsx [hunk 2]
```diff
@@ -26,9 +27,12 @@ void features.add(import.meta.url, {
 		'g 2': 'Go to Commits',
 		'g 3': 'Go to Checks',
 		'g 4': 'Go to Files changed',
+		'g →': 'Go to next PR tab',
+		'g ←': 'Go to previous PR tab',
 	},
 	include: [
 		pageDetect.isPR,
 	],
+	deduplicate: false,
```
Comment (cheap-glitch) [inline source/features/pull-request-hotkey.tsx:36]: We need this since we're moving between PR tabs

File: source/features/pull-request-hotkey.tsx [hunk 3]
```diff
@@ -4,19 +4,20 @@ import * as pageDetect from 'github-url-detection';
 import features from '.';
 
 function init(): void {
-	const tabs = select.all('.tabnav-tabs .tabnav-tab');
-	const selectedIndex = tabs.indexOf(select('.tabnav-tabs .selected')!);
+	const tabs = select.all('.tabnav-tabs a.tabnav-tab');
```
Comment (cheap-glitch) [inline source/features/pull-request-hotkey.tsx:7]: `a` excludes some buttons which also have `.tabnav-tab` for some reason

**Review by cheap-glitch — COMMENTED** [review]
**Note:** the numeric shortcuts only work on a Qwerty layout! This is a GitHub bug that affects every shortcut, whether they're native or added by RGH (e.g. <kbd>?</kbd> doesn't work on Azerty).

**Comment by cheap-glitch** [comment]
I think it'd make sense to rename this feature `pull-request-hotkeys` while we're at it.

**Comment by fregante** [comment]
> **Note:** the numeric shortcuts only work on a Qwerty layout! This is a GitHub bug that affects every shortcut, whether they're native or added by RGH (e.g. ? doesn't work on Azerty).

I finally saw this:

```js
document.addEventListener('keydown', (event: Event) => {
  if (!(event instanceof KeyboardEvent)) return
  if (!isShortcutAllowed(event)) return

  if (event.target instanceof Node && isFormField(event.target)) return
  if (eventToHotkeyString(event) !== 'Shift+?') return
  showKeyboardShortcuts()
})
```

Their hotkey detection code makes no sense as the shortcut is never `Shift+?` but `Shift+/` on US keyboards. The funny part is that `eventToHotkeyString` correctly returns `?` on a Thai keyboard so it fails that test.

File: source/features/pull-request-hotkey.tsx (hunk 3 above)
Comment (fregante) [reply source/features/pull-request-hotkey.tsx:7]: Worth adding a comment explaining what these are

File: source/features/pull-request-hotkey.tsx (hunk 1 above)
Comment (fregante) [reply source/features/pull-request-hotkey.tsx:20]: Looks like something I'd write, but https://www.youtube.com/watch?v=sTMgX1PDGAE

File: source/features/pull-request-hotkey.tsx (hunk 3 above)
Comment (cheap-glitch) [reply source/features/pull-request-hotkey.tsx]: Replaced it with a better and self-explanatory selector.

**Comment by cheap-glitch** [comment]
> > **Note:** the numeric shortcuts only work on a Qwerty layout! This is a GitHub bug that affects every shortcut, whether they're native or added by RGH (e.g. ? doesn't work on Azerty).
> 
> You asked [the same thing](https://github.com/refined-github/refined-github/issues/4962#issuecomment-948666696) months ago smile

And it's still broken… Plus a new bug appeared recently: pressing Shift or Ctrl _on its own_ opens up the command palette, making every keyboard shortcut unusable :man_facepalming:

**Comment by fregante** [comment]
Is this PR good to go? Let's merge it

**Comment by kidonng** [comment]
I just noticed this feature has been renamed, but no migration is added 🤔

**Comment by cheap-glitch** [comment]
> I just noticed this feature has been renamed, but no migration is added thinking

Done in https://github.com/refined-github/refined-github/commit/62498a6a2cb896a182059b8eba27f778920b700e, thanks for catching that up!

**Comment by kidonng** [comment]
Actually, let's do #5438 😉
