### PR TITLE
Meta: fix `waitForElement` and `once` parameter of `observe`

### LINKED ISSUE #9257: The `once` parameter of the `observe` helper is useless
### Description

**Expected behavior:** The registered listener is removed after the target element is found.

**Actual behavior:** The registered  listener is removed after the first animation triggers anywhere on the document, regardless of the element or animation name.

**The reason:** The `once` parameter is just passed to `globalThis.addEventListener('animationstart')`.

https://github.com/refined-github/refined-github/blob/c0e15f48290869d944227bcb4dab5b31e3473e90/source/helpers/selector-observer.tsx#L88-L102

### How to replicate the issue + URL

\-

### Extension version

26.4.20

### PR DESCRIPTION
**Pull request by SunsetTechuila**
Fixes #9257

### CODE REVIEW

File: source/helpers/selector-observer.tsx [hunk 1]
```diff
@@ -47,6 +47,12 @@ export default function observe<
 		signal = signal ? AbortSignal.any([signal, delayedDomReady]) : delayedDomReady;
 	}
 
+	let onceController: AbortController | undefined;
+	if (once) {
+		onceController = new AbortController();
+		signal = signal ? AbortSignal.any([signal, onceController.signal]) : onceController.signal;
```
Comment (fregante) [inline source/helpers/selector-observer.tsx]: signal = mergeSignals(signal, onceController);

https://github.com/fregante/abort-utils/blob/main/source/merge-signals.md

Feels like I should add a new helper like `new AbortController(existingSignalIfAny)` to wrap both assignments, but it might be too much

**Review by fregante — APPROVED** [review]

File: source/helpers/selector-observer.tsx [hunk 2]
```diff
@@ -98,7 +108,8 @@ export default function observe<
 		target.classList.add(seenMark);
 
 		listener(target, {signal});
-	}, {once, signal});
+		onceController?.abort();
+	}, {signal});
 }
 
 // Untested, likely breaks due to wrong `ancestor` level
```
Comment (fregante) [inline source/helpers/selector-observer.tsx]: Also note this. The `once` feature was added "just in case" but never tested because it was never needed. This is partly why I don't like "just in case" code.

Comment (SunsetTechuila) [reply source/helpers/selector-observer.tsx]: https://github.com/refined-github/refined-github/pull/9259

Comment (fregante) [reply source/helpers/selector-observer.tsx]: Where is `waitForElement` changed? That PR doesn't affect what I'm talking about

Comment (SunsetTechuila) [reply source/helpers/selector-observer.tsx]: `waitForElement` is working now

File: source/helpers/selector-observer.tsx [hunk 3]
```diff
@@ -98,27 +108,23 @@ export default function observe<
...
 
-// Untested, likely breaks due to wrong `ancestor` level
 export async function waitForElement<
 	Selector extends string,
 	ExpectedElement extends ParseSelector<Selector, HTMLElement | SVGElement>,
 >(
 	selectors: Selector | readonly Selector[],
 	{signal, stopOnDomReady}: Options = {},
 ): Promise<ExpectedElement | void> {
-	const local = new AbortController();
```
Comment (SunsetTechuila) [inline source/helpers/selector-observer.tsx:112]: What is its use?

Comment (fregante) [reply source/helpers/selector-observer.tsx:112]: Ask 2025 fregante. That rascal committed code without testing it

File: source/helpers/selector-observer.tsx [hunk 4]
```diff
@@ -98,27 +108,28 @@ export default function observe<
...
 	return new Promise<ExpectedElement | void>(resolve => {
 		observe<Selector, ExpectedElement>(selectors, element => {
 			resolve(element);
-			local.abort();
-		}, {signal, stopOnDomReady, once: true});
+		}, {
+			signal,
+			stopOnDomReady,
+			once: true,
+			ancestor: 4,
```
Comment (SunsetTechuila) [inline source/helpers/selector-observer.tsx:129]: Image

Image

`getCallerId` adds 1 to `ancestor`. Default is 1

Comment (fregante) [reply source/helpers/selector-observer.tsx:129]: I can't guarantee it just by looking at it. Try calling waitForElement twice in sequence and see what the ID is. If it's the same, then it's wrong. Two calls should have two different IDs

Comment (SunsetTechuila) [reply source/helpers/selector-observer.tsx:129]: I tweaked the value first and only then asked Copilot to explain it. So yes, it's tested

Comment (SunsetTechuila) [reply source/helpers/selector-observer.tsx:129]: image
