### PR TITLE
`esc-to-cancel` - Restore feature on PRs

### LINKED ISSUE #9250: `esc-to-cancel` broken on new PR view
See context in https://github.com/refined-github/refined-github/issues/8946

### Test URL

https://github.com/refined-github/sandbox/pull/1

### PR DESCRIPTION
**Pull request by anasm266**
Fixes #9250

## Test URLs
- https://github.com/refined-github/sandbox/pull/1

## Demo gif

(

https://github.com/user-attachments/assets/c4fca0cb-3bef-44a2-a47e-9bcdb4b02c7c

### CODE REVIEW

File: source/features/esc-to-cancel.tsx [hunk 1]
```diff
@@ -1,14 +1,50 @@
...
+const titleContainerSelectors = [
+	'form', // Title edit form
+	'[class^="prc-PageHeader-Title"]', // New PR title wrapper
+	'[class^="prc-PageLayout-Header"]', // New PR header
+	'.gh-header-title', // Old issue/PR header
+];
+
+function findCancelButton(field: HTMLInputElement): HTMLButtonElement | HTMLAnchorElement | undefined {
+	for (const titleContainerSelector of titleContainerSelectors) {
+		const titleContainer = field.closest(titleContainerSelector);
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: No loop needed, just pass the whole array to .closest()

File: source/features/esc-to-cancel.tsx [hunk 2]
```diff
@@ -1,14 +1,50 @@
...
+		if (!titleContainer) {
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: closest() must/will find the element, so no condition needed here

File: source/features/esc-to-cancel.tsx [hunk 3]
```diff
@@ -1,14 +1,50 @@
...
+			continue;
+		}
+
+		const localCancelButton = [...titleContainer.querySelectorAll<HTMLButtonElement>('button:not([disabled])')]
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: $$() already selects, returns an array, and is properly typed:
```suggestion
		const localCancelButton = $$('button:not([disabled])')
```

File: source/features/esc-to-cancel.tsx [hunk 4]
```diff
@@ -1,14 +1,50 @@
...
+			.find(button => normalizeText(button.textContent ?? '') === 'Cancel');
+		if (localCancelButton) {
+			return localCancelButton;
+		}
+	}
+
+	return $optional<HTMLButtonElement | HTMLAnchorElement>('.js-cancel-issue-edit');
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: This cannot be optional. The button must be found. If it's not found, the selectors are wrong and/or GitHub was updated. In both cases we want an error to be thrown (`$()` will throw, `$optional()` doesn't)

File: source/github-events/on-field-keydown.tsx [hunk 5]
```diff
@@ -1,18 +1,19 @@
...
+	delegate<DelegateField, 'keydown'>(selector, 'keydown', event => {
 		const field = event.delegateTarget;
 
 		if (
 			event.isComposing
 			// New autocomplete dropdown
 			|| field.hasAttribute('aria-autocomplete')
 			// Classic autocomplete dropdown
-			|| elementExists('.suggester', field.form!)
+			|| elementExists('.suggester', field.form ?? undefined)
```
Comment (fregante) [inline source/github-events/on-field-keydown.tsx]: Don't make unnecessary changes

File: source/features/esc-to-cancel.tsx [hunk 6]
```diff
@@ -1,14 +1,50 @@
...
+
+function handleEscPress(event: DelegateEvent<KeyboardEvent, HTMLInputElement | HTMLTextAreaElement>): void {
 	if (event.key === 'Escape') {
-		$('.js-cancel-issue-edit').click();
+		if (!(event.delegateTarget instanceof HTMLInputElement)) {
+			return;
+		}
+
+		const cancelButton = findCancelButton(event.delegateTarget);
+		if (!cancelButton) {
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: As mentioned, the cancel button must be found

**Review by fregante — CHANGES_REQUESTED** [review]

**Comment by fregante** [comment]
Note that untested AI PRs will result in a block. So make sure it works and ideally record a screencast or gif (with LICEcap if you use macos for example)

**Comment by anasm266** [comment]
https://github.com/user-attachments/assets/109b9216-ab03-4759-a9f5-879287f004c2

File: source/features/esc-to-cancel.tsx [hunk 7]
```diff
@@ -1,14 +1,35 @@
...
+const titleContainerSelectors = [
+	'form', // Title edit form
+	'[class^="prc-PageHeader-Title"]', // New PR title wrapper
+	'[class^="prc-PageLayout-Header"]', // New PR header
+	'.gh-header-title', // Old issue/PR header
+];
+
+function findCancelButton(field: HTMLInputElement): HTMLButtonElement | HTMLAnchorElement {
+	const titleContainer = field.closest(titleContainerSelectors.join(','))!;
+	return $$('button:not([disabled])', titleContainer)
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: Without changing the order of operations, we have to temporarily use `$$optional` here or else it might throw on the old version.

**Review by fregante — APPROVED** [review]
Thank you! Looks reasonable already

File: source/features/esc-to-cancel.tsx [hunk 8]
```diff
@@ -1,14 +1,35 @@
...
 
-function handleEscPress(event: DelegateEvent<KeyboardEvent>): void {
+function normalizeText(text: string): string {
+	return text.replaceAll(/\s+/g, ' ').trim();
+}
+
+const titleContainerSelectors = [
+	'form', // Title edit form
+	'[class^="prc-PageHeader-Title"]', // New PR title wrapper
+	'[class^="prc-PageLayout-Header"]', // New PR header
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]: Out of these 3, only one should be needed, I reckon. Which one does the PR header have? Make sure it exists on both the Conversation and Files Changed tab.

File: source/features/esc-to-cancel.tsx [hunk 9]
```diff
@@ -1,14 +1,33 @@
...
+
+const titleContainerSelectors = [
+	'[class^="prc-PageLayout-Header"]', // New PR header
+	'.gh-header-title', // Old issue/PR header
+];
+
+function findCancelButton(field: HTMLInputElement): HTMLButtonElement | HTMLAnchorElement {
+	const titleContainer = field.closest(titleContainerSelectors);
+	return $$optional('button:not([disabled])', titleContainer ?? undefined)
+		.find(button => normalizeText(button.textContent) === 'Cancel')
```
Comment (SunsetTechuila) [inline source/features/esc-to-cancel.tsx]: When `normalizeText` is needed?

File: source/features/esc-to-cancel.tsx [hunk 10]
```diff
@@ -1,14 +1,33 @@
...
+}
+
+const titleContainerSelectors = [
+	'[class^="prc-PageLayout-Header"]', // New PR header
+	'.gh-header-title', // Old issue/PR header
+];
+
+function findCancelButton(field: HTMLInputElement): HTMLButtonElement | HTMLAnchorElement {
+	const titleContainer = field.closest(titleContainerSelectors);
+	return $$optional('button:not([disabled])', titleContainer ?? undefined)
```
Comment (SunsetTechuila) [inline source/features/esc-to-cancel.tsx]: @fregante allow `baseElements` in `select-dom` to be `null` 🙏

File: source/features/esc-to-cancel.tsx (hunk 9 above)
Comment (anasm266) [reply source/features/esc-to-cancel.tsx]: checked and the button text is exactly Cancel, so normalizeText isn’t needed here. I only need the label match because the header container includes multiple buttons.

File: source/features/esc-to-cancel.tsx (hunk 10 above)
Comment (fregante) [reply source/features/esc-to-cancel.tsx]: I follow https://github.com/sindresorhus/meta/discussions/7

I guess an exception can be made since the DOM has a lot of nulls. PR welcome to explore it further

**Review by SunsetTechuila — APPROVED** [review]

File: source/features/esc-to-cancel.tsx [hunk 11]
```diff
@@ -7,8 +7,20 @@ import {onConversationTitleFieldKeydown} from '../github-events/on-field-keydown
...
+		if (!(event.delegateTarget instanceof HTMLInputElement)) {
+			return;
+		}
+
+		const cancelButton = $([
+			'div[class^="prc-PageLayout-HeaderContent"] > form button[data-variant="invisible"]',
+			// Old view -- TODO: Remove after legacy PR files view is removed
+			'.js-cancel-issue-edit',
+		]);
+		if (cancelButton.textContent.trim() !== 'Cancel') {
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx:19]: We have assertNodeContent

File: source/features/esc-to-cancel.tsx [hunk 12]
```diff
@@ -18,14 +30,11 @@ function init(signal: AbortSignal): void {
 	onConversationTitleFieldKeydown(handleEscPress, signal);
 }
 
-// TODO: Drop in March 2025, implemented by GitHub
-// https://github.com/refined-github/refined-github/pull/7892
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx:22]: We still want a TODO comment to check if GitHub is already handling the keypress or not. September 2026 would be good, then every 6 months or so.

File: source/features/esc-to-cancel.tsx [hunk 13]
```diff
@@ -35,8 +44,8 @@ void features.add(import.meta.url, {
 
 Test URLs:
 
-1. Visit https://github.com/issues?q=+archived%3Afalse+author%3A%40me
-2. Open any issue/PR
+1. Visit https://github.com/issues?q=archived%3Afalse%20author%3A%40me%20type%3Apr
```
Comment (fregante) [inline source/features/esc-to-cancel.tsx]:
```suggestion
1. Visit https://github.com/pulls
```

I'm not sure why I made this so complicated back then

File: source/features/esc-to-cancel.tsx (hunk 11 above)
Comment (SunsetTechuila) [reply source/features/esc-to-cancel.tsx:19]: Which works only with text nodes or elements containing only them

Comment (fregante) [reply source/features/esc-to-cancel.tsx:19]: Therefore the code can be adjusted to use it, what's the issue? `cancelButton.firstChild` probably.

Comment (SunsetTechuila) [reply source/features/esc-to-cancel.tsx:19]: The issue is that it would be `cancelButton.firstChild.firstChild`

Comment (SunsetTechuila) [reply source/features/esc-to-cancel.tsx:19]: Or `cancelButton.querySelector('span[data-component="text"]')`. I like neither
