### PR TITLE
`show-names` - Exclude invalid elements on new dashboard

### LINKED ISSUE #6915: `show-names` broken on GitHub dashboard's follwed article.
### Description

`show-names` on dashboard page's followed article is broken.

`김정현` is already user's name and user's key is next of it's name with `kimjh11130`.
image
image

### How to replicate the issue + URL

Go dashbord (https://github.com/dashboard) and find `followed article`.

### Extension version

23.9.7

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by 134130**
## Description
- Closes #6915 
- Fix `show-names` fetches redundant username on `followed article` in `GitHub newsfeed`

## Test URLs
- https://github.com/ (some followed article)

## Screenshot
image

### CODE REVIEW

**Comment by 134130** [comment]
There is two options for fixing this issue. 
- Only enable `show-names` on article's header user [`5382431` (#6916)](https://github.com/refined-github/refined-github/pull/6916/commits/53824312f5335f834bcd24326f40f7735127b3b3)
- Filter `show-names` with it's link validation [`70356a7` (#6916)](https://github.com/refined-github/refined-github/pull/6916/commits/70356a77a9046c8d92508d74702267d8d27a2c55)

I think 2nd one looks better

**Comment by 134130** [comment]
Both are verified

File: source/features/show-names.tsx [hunk 1]
```diff
@@ -16,7 +16,8 @@ const batchUpdateLinks = batchedFunction(async (batchedUsernameElements: HTMLAnc
 	const myUsername = getUsername();
 	for (const element of new Set(batchedUsernameElements)) {
 		const username = element.textContent;
-		if (username && username !== myUsername && username !== 'ghost') {
+
+		if (username && username !== myUsername && username !== 'ghost' && element.href.endsWith(`/${username}`)) {
```
Comment (fregante) [inline source/features/show-names.tsx:20]: When does this not end with /username?

Comment (134130) [reply source/features/show-names.tsx:20]: You can see on my description.

In my case the element's textContent is '김정현' and href is 'ki.jh11012'.
'김정현' is user's nickname not github username. So in this feature, no need to query its nickname since it is already showing.

Comment (fregante) [reply source/features/show-names.tsx:20]: If the selector is selecting the wrong thing, maybe we should alter it. Is there any simple change that would avoid this selection? For example by appending `:not(.followed *)` if that class exists on a parent

Comment (134130) [reply source/features/show-names.tsx:20]: I'll digging is there some way to specifying these with css selector.

Comment (134130) [reply source/features/show-names.tsx:20]: I think there is no way to detect `followed` article just with css selector.

Comment (fregante) [reply source/features/show-names.tsx:20]: `:not([aria-label="card content"] *)`

Comment (fregante) [reply source/features/show-names.tsx:20]: This href-based condition fails when people set the same name, for example (no RGH enabled)

Screenshot

Comment (134130) [reply source/features/show-names.tsx:20]: - It have been tried to excluding card content before on this issue.
  - https://github.com/refined-github/refined-github/issues/6530
- Since `:not([aria-label="card content"] *)` can avoid above case also, just using it and discarded old selector: `:not(.color-shadow-medium a)`

Comment (fregante) [reply source/features/show-names.tsx:20]: Thanks for the change! I think we can drop this exclusion though, I'd rather tweak the selector over time if necessary

Comment (134130) [reply source/features/show-names.tsx:20]: Oops, sorry. I'll drop it

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
I feel like we should start naming PRs with the name of the feature first, it will make for a more readable release log as well as commit list

**Comment by yakov116** [comment]
Agree 👍
