### PR TITLE
Fix `html-preview-link` in new file UI

### LINKED ISSUE #6360: `html-preview-link` missing from new file UI
### Description

Screenshot

### How to replicate the issue + URL

https://github.com/CodingTrain/website-archive/blob/4f90eedb9618257d9166241e92e51a7f3f00a08e/code_challenges/PerlinNoiseTerrain_p5.js/index.html

### Extension version

23.2.1

### Browser(s) used

safari

### PR DESCRIPTION
**Pull request by kidonng**
Fix #6360

## Test URLs

https://github.com/CodingTrain/website-archive/blob/4f90eedb9618257d9166241e92e51a7f3f00a08e/code_challenges/PerlinNoiseTerrain_p5.js/index.html

## Screenshot

image

### CODE REVIEW

File: source/features/html-preview-link.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ function add(rawButton: HTMLAnchorElement): void {
 		.parentElement! // `BtnGroup`
 		.prepend(
 			<a
-				className="btn btn-sm BtnGroup-item rgh-html-preview-link"
+				className="btn btn-sm BtnGroup-item"
```
Comment (kidonng) [inline source/features/html-preview-link.tsx:18]: Added in https://github.com/refined-github/refined-github/commit/86c0a731a3bb123b7a48fb0e2e21f4192df4fb46#diff-5a0d6407fb78a28cac196b6bf9d7f6e9eccaa02e5098d74df02eb70991c5ee5c for deduplicate, no longer used

File: source/features/html-preview-link.tsx [hunk 2]
```diff
@@ -25,7 +25,7 @@ function add(rawButton: HTMLAnchorElement): void {
 }
 
 function init(signal: AbortSignal): void {
-	observe('a#raw-url', add, {signal});
+	observe('a:is(#raw-url, [data-testid="raw-button"])', add, {signal});
```
Comment (kidonng) [inline source/features/html-preview-link.tsx:28]: Not sure if this "testid" thing will persist, good enough for now

**Review by fregante — APPROVED** [review]
