### PR TITLE
`conflict-marker` - Add support for new issue view

### LINKED ISSUE #8264: `conflict-marker`: doesn't work
### Description

Image

### How to replicate the issue + URL

https://github.com/refined-github/sandbox/issues?q=conflict

### Extension version

25.1.24

### Browser(s) used

firefox, zen

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by Harrish92**
closes #8264

## Test URLs
https://github.com/refined-github/sandbox/issues?q=conflict

## Screenshot
Screenshot From 2025-02-11 02-02-38

### CODE REVIEW

File: source/github-helpers/selectors.ts [hunk 1]
```diff
@@ -77,6 +77,14 @@ export const openPrsListLink_ = [
 	[4, 'https://github.com/refined-github/sandbox/issues?q=conflict'],
 ] satisfies UrlMatch[];
 
+// `cRyBKI` represents an open PR and `.knLhXt` a Draft PR
+export const openPrsListInIssuesLink = css`
+.PullRequestRow-module__row--ogYMh:has(
+	.cRyBKI,
+	.knLhXt
+) a.Title-module__anchor--SyQM6
+`;
```
Comment (kovsu) [inline source/github-helpers/selectors.ts:86]: I think the code is dynamically generated and can change which is unstable. It's also quite obscure.

Comment (Harrish92) [reply source/github-helpers/selectors.ts]: @kovsu

I made the code more robust to changes.

File: source/features/conflict-marker.tsx [hunk 2]
```diff
@@ -29,14 +29,17 @@ async function addIcon(links: HTMLAnchorElement[]): Promise<void> {
 		${key}: repository(owner: "${owner}", name: "${name}") {
 			pullRequest(number: ${number}) {
 				mergeable
+                state
+                isDraft
```
Comment (fregante) [inline source/features/conflict-marker.tsx:33]: Indentation should use tabs

File: source/features/conflict-marker.tsx [hunk 3]
```diff
@@ -53,6 +56,7 @@ async function addIcon(links: HTMLAnchorElement[]): Promise<void> {
 async function init(signal: AbortSignal): Promise<void> {
 	await expectToken();
 	observe(openPrsListLink, batchedFunction(addIcon, {delay: 100}), {signal});
+	observe(PrsListInOpenIssuesLink, batchedFunction(addIcon, {delay: 100}), {signal});
```
Comment (fregante) [inline source/features/conflict-marker.tsx:59]: `PrsListInOpenIssuesLink` is the same as `openPrsListLink`, it shouldn't be a new selector/observer. Please add the new selector to `openPrsListLink`, which can be turned into an array, probably exactly this:

```js
export const openPrsListLink = [
	// `.color-fg-open` is needed because of the icon added by `highlight-non-default-base-branch`
	css`
		.js-issue-row:has(
			.octicon-git-pull-request.color-fg-open,
			.octicon-git-pull-request-draft
		) a.js-navigation-open
	`,
	// React view
	css`
		li[role="listitem"] a[data-hovercard-url*="/pull"]
	`,
];
```

**Comment by fregante** [comment]
@Harrish92 thanks for the PR! I left some notes

File: source/github-helpers/selectors.ts [hunk 4]
```diff
@@ -66,13 +66,20 @@ export const prCommitStatusIcon_ = [
...
+	// `.color-fg-open` is needed because of the icon added by `highlight-non-default-base-branch`
+	css`
+		.js-issue-row:has(
+			.octicon-git-pull-request.color-fg-open,
+			.octicon-git-pull-request-draft
+		) a.js-navigation-open
+	`,
+	// React view
+	css`
+		li[role="listitem"] a[data-hovercard-url*="/pull"]
```
Comment (fregante) [inline source/github-helpers/selectors.ts:79]: The state can now be found on a parent of the `a` that is being selected:

> aria-label="<code>quick-comment-edit</code> - Support new issue view: Status: Draft (not ready). Add author fregante to current search query. More information available below."

> aria-label="<code>conflict-marker</code> - Add support for new issue view: Status: Open (in progress). Add author Harrish92 to current search query. More information available below."

So you can replace that `li[role="listitem"]` with:

```css
li:is(
	[aria-label*="Status: Open (in progress)"],
	[aria-label*="Draft (not ready)"]
) a[data-hovercard-url*="/pull"]
```

Comment (Harrish92) [reply source/github-helpers/selectors.ts:79]: @fregante 

Originally, this is how the selector was implemented, however aria-label also contains the title of the issue. This may cause problems down the road as the title may contain the selector's text. Even though this scenario is unlikely, this code is imo more vulnerable to changes.
