### PR TITLE
`locked-issue` - Restore feature on PRs

### LINKED ISSUE #8935: `locked-issue` broken on PR pages
### Description

Image

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pull/7796

### Extension version

26.1.24

### Browser(s) used

Microsoft Edge 145.0.3800.22 (Official build) beta (64-bit)

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
fixes #8935

#8946

affects `netiquette` and `rgh-netiquette`

## Test URLs

https://github.com/refined-github/refined-github/pull/7796

## Screenshot

image

image

### CODE REVIEW

File: source/features/locked-issue.tsx [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
 import * as pageDetect from 'github-url-detection';
-import {elementExists} from 'select-dom';
-import {$} from 'select-dom/strict.js';
 
 import features from '../feature-manager.js';
 import observe from '../helpers/selector-observer.js';
 import isConversationLocked from '../github-helpers/is-conversation-locked.js';
+import {getIdentifiers} from '../helpers/feature-helpers.js';
+
+export const {class: featureClass, selector: featureSelector} = getIdentifiers(import.meta.url);
```
Comment (SunsetTechuila) [inline source/features/locked-issue.tsx:11]: for `jump-to-conversation-close-event`

**Review by fregante — APPROVED** [review]
