### PR TITLE
`quick-review` - Fix missing emoji in toast notification

### LINKED ISSUE #9156: `quick-review` - Emoji sometimes missing from toast
### Description

Weird:

Image

This is the dom:

Image

### How to replicate the issue + URL

https://github.com/refined-github/sandbox/pull/49

### Extension version

26.3.21

### Browser(s) used

Safari 18.4

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
Fixes #9156

### CODE REVIEW

File: source/features/quick-review.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ import {
 import {randomArrayItem} from '../helpers/math.js';
 import {getToken} from '../options-storage.js';
 
-const emojis = [...'🚀🐿️⚡️🤌🥳🥰🤩🥸😎🤯🚢🛫🏳️🏁'];
+const emojis = ['🚀', '🐿️', '⚡️', '🤌', '🥳', '🥰', '🤩', '🥸', '😎', '🤯', '🚢', '🛫', '🏳️', '🏁'];
```
Comment (fregante) [inline source/features/quick-review.tsx:21]: Or
```suggestion
const emojis = [...'🚀🐿⚡🤌🥳🥰🤩🥸😎🤯🚢🛫🏳🏁'];
```

If you run this magic piece of code, you'll find the empty strings gone 😅

Comment (SunsetTechuila) [reply source/features/quick-review.tsx:21]: 🤨

image

**Comment by SunsetTechuila** [comment]
Here is a sane explanation:

## The Problem: UTF-16 Surrogate Pairs

JavaScript strings are encoded in **UTF-16**, not Unicode code points. Most emojis require **two UTF-16 code units** (a surrogate pair) to represent a single character.

The spread operator `[...str]` is *supposed* to be Unicode-aware — and it is for **simple emojis**. That's why most emojis in your result look correct.

### Why the count is 17 instead of 14

The 3 extra elements come from **multi-codepoint emojis** — specifically emojis built from sequences joined by a **Zero Width Joiner (ZWJ, U+200D)** or **variation selectors / modifier sequences**.

For example:
- 🏳️‍🌈 is actually: `🏳` + `️` (variation selector) + `‍` (ZWJ) + `🌈` — multiple codepoints
- 🏁 (checkered flag) can be a flag sequence: two **Regional Indicator** codepoints combined

`[...str]` splits by **Unicode code points**, so it correctly handles surrogate pairs, but it **cannot keep ZWJ sequences together** — it splits them into their individual constituent codepoints, producing extra array elements.

### Quick illustration

```js
const flag = "🏳️‍🌈";
console.log(flag.length);      // 6 (UTF-16 code units)
console.log([...flag].length); // 4 (code points: 🏳 + ️ + ZWJ + 🌈)
// spread still splits the ZWJ sequence into 4 separate elements
```

### The fix: `Intl.Segmenter`

```js
const str = '🚀🐿⚡🍌🥹🤩😡🤓😎🐻🚢✈️🏁🏁';
const emojis = [...new Intl.Segmenter().segment(str)].map(s => s.segment);
console.log(emojis.length); // 14 ✓
```

`Intl.Segmenter` understands **grapheme cluster boundaries** — it keeps ZWJ sequences, variation selectors, and modifier sequences together as a single perceived character.

### Summary

| Method | Splits on | Handles surrogate pairs | Handles ZWJ sequences |
|---|---|---|---|
| `str[i]` / `.length` | UTF-16 code units | ✗ | ✗ |
| `[...str]` | Unicode code points | ✓ | ✗ |
| `Intl.Segmenter` | Grapheme clusters | ✓ | ✓ |

**Comment by fregante** [comment]
That _still_ doesn't explain it 😅 

The explanation is that those extra characters are asking the renderer to render an emoji instead of the non-colored glyph

**Review by fregante — APPROVED** [review]

File: source/features/quick-review.tsx (hunk 1 above)
Comment (fregante) [reply source/features/quick-review.tsx:21]: I thought you were on macOS too

Screenshot
