### PR TITLE
`pr-jump-to-first-non-viewed-file` - Fix click conflicts

### LINKED ISSUE #8610: Clicking "filter files" on the new GitHub PR UI focuses the first file (`pr-jump-to-first-non-viewed-file`)
### Description

When using the new GitHub PR UI with the file sidebar collapsed, clicking "filter files" focuses the first file in the diff.

https://github.com/user-attachments/assets/224eaf90-ec57-4c7f-9b6e-a9b3db67e921

### How to replicate the issue + URL

URL: https://github.com/refined-github/refined-github/pull/7893/files#diff-1f030558c26a119b6a5dbc32e43a9c76f179432153278e04028b5e302158963b

1. Collapse left sidebar
2. Click "filter files" in the top toolbar

### Extension version

25.8.4

### Browser(s) used

Arc

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #8610

## Test URLs

This PR's Files tab

## Screenshot

insider

### CODE REVIEW

File: source/features/pr-jump-to-first-non-viewed-file.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ function jumpToFirstNonViewed(): void {
 
 const selectors = [
 	'.diffbar-item progress-bar', // TODO: Old PR Files view, drop in 2026
-	'section[class*="PullRequestFilesToolbar-module"] > div:last-child',
```
Comment (fregante) [inline source/features/pr-jump-to-first-non-viewed-file.tsx:24]: This was selecting the whole chunk of buttons including "Submit review"
