### PR TITLE
Fix: `user-local-time` breaks positioning of some hovercards

### LINKED ISSUE #4527: `user-local-time` breaks positioning of some hovercards
Go to https://github.com/sindresorhus/refined-github and hover on the contributors avatars:

image

This is caused by the CSS added in https://github.com/sindresorhus/refined-github/pull/4384. The weird thing is that it happens on some hovercards but not all. I don't know if it's the "Sponsor" button or the "Committed to this repo" notice which makes this bug appear (or both).

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4527 

## Test URLs

To check the cropping issue isn't back:
 * https://togithub.com/refined-github/refined-github/issues/4285
 * https://togithub.com/hexalellogram/iPhoneBatteryClient

## Screenshot

https://user-images.githubusercontent.com/46634000/141319805-305ded44-20a2-4f85-b0bd-ae33d2679661.mp4

### CODE REVIEW

File: source/features/user-local-time.tsx [hunk 1]
```diff
@@ -109,6 +109,8 @@ async function insertUserLocalTime(hovercardContainer: Element): Promise<void> {
 	// Adding the time element might change the height of the hovercard and thus break its positioning
 	const hovercardHeight = hovercard.offsetHeight;
 
+	// Only remove the reserved space when the time element is actually inserted in the hovercard to avoid #4527
+	hovercardContainer.classList.add('rgh-user-local-time-added');
```
Comment (cheap-glitch) [inline source/features/user-local-time.tsx:113]: The idea is to use two classes, one for de-duplication (added as soon as possible), the other to remove the space reserved via CSS (added as late as possible).
