### PR TITLE
`linkify-code`, `linkify-symbolic-links` - Fix scrolling & links duplication

### LINKED ISSUE #8988: `linkify-code`, `linkify-symbolic-links` - Links are duplicated when switching between "Code" and "Blame" tabs
### Description

I've made the links red for a demonstration:

https://github.com/user-attachments/assets/01f5c422-f674-4345-b05e-e96b06178520

### How to replicate the issue + URL

https://github.com/wmluke/angular-flash/blob/0.1.14/app/components

https://github.com/refined-github/refined-github/blob/2e4b03c26398a1b65a5efb0438c8a44cdedebdec/source/features/linkify-code.tsx

### Extension version

2e4b03c26398a1b65a5efb0438c8a44cdedebdec

### Browser(s) used

Microsoft Edge 145.0.3800.58 (Official build) beta (64-bit) 

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
fixes #8988

fixes https://github.com/refined-github/refined-github/pull/8878#issuecomment-3809636178

## Test URLs

https://github.com/refined-github/refined-github/blob/2e4b03c26398a1b65a5efb0438c8a44cdedebdec/source/features/linkify-code.tsx

https://github.com/wmluke/angular-flash/blob/0.1.14/app/components

### CODE REVIEW

File: source/github-helpers/dom-formatters.tsx
Comment (SunsetTechuila) [inline source/github-helpers/dom-formatters.tsx]: This function needs a new name

File: source/refined-github.css [hunk 1]
```diff
@@ -205,6 +205,10 @@ div[data-target='readme-toc.content'] div.blob-wrapper img {
 	position-area: center;
 	padding: 0 !important;
 	z-index: 2;
+	pointer-events: auto;
```
Comment (SunsetTechuila) [inline source/refined-github.css:208]: Didn't know this was possible when I opened the previous PR

Image

**Comment by SunsetTechuila** [comment]
I don't think was a good idea to create a release before merging this PR

**Comment by SunsetTechuila** [comment]
You asked if you should release an update, but I figured you wouldn't since I didn't say "yes", broken `netiquette` got disabled via hotfix, and you knew about #8988

**Review by fregante — APPROVED** [review]
