### PR TITLE
Fix `use-first-commit-message-for-new-prs`

### LINKED ISSUE #5108: `use-first-commit-message-for-new-prs` is broken
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### Description

```
❌ use-first-commit-message-for-new-prs 0.0.0 → TypeError: select_dom__WEBPACK_IMPORTED_MODULE_0__["default"](...) is undefined
    init moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:15144
    runFeature moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8049
    setupPageLoad moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8067
    add moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8125
    tsx moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:15148
    __webpack_require__ moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25616
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25838
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:26088
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:26090
refined-github.js:7972:11

```

This selector is probably broken:
https://github.com/refined-github/refined-github/blob/a07d721502d6d9308c994c0a010bc5356df6a651/source/features/use-first-commit-message-for-new-prs.tsx#L15

### Example URL

https://github.com/refined-github/refined-github/compare/add-multiple-prs-dropdown

### Browser(s) used

Firefox 94

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5108 

## Test URLs

https://github.com/refined-github/refined-github/compare/add-multiple-prs-dropdown?expand=1

## Screenshot

<table>
<tr>
	<td>

**Before**
	<td>

**After**
<tr>
	<td>

screenshot-1638195347
	<td>

screenshot-1638195085
</table>

### CODE REVIEW

File: source/features/use-first-commit-message-for-new-prs.tsx [hunk 1]
```diff
@@ -12,7 +12,11 @@ async function init(): Promise<void | false> {
 		return false;
 	}
 
-	const [prTitle, ...prMessage] = select('#commits_bucket [data-url$="compare/commit"] a[title]')!.title.split(/\n\n/);
+	// TODO [2022-05-01]: Remove GHE code
```
Comment (fregante) [inline source/features/use-first-commit-message-for-new-prs.tsx:15]: Which one? This needs to be on the relevant line as `// TODO [date] GHE`

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
# 🙏
