### PR TITLE
Avoid misplacement of `useful-forks`

### LINKED ISSUE #6049: `useful-forks` conflicts with `comments-time-machine-links`
### Description

Wrong position:

Screen Shot 5

### How to replicate the issue

1.https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md?rgh-link-date=2022-01-16T06%3A22%3A48Z

### Extension version

22.9.9

### Browser(s) used

Safari

### PR DESCRIPTION
**Pull request by fregante**
- Closes #6049

## Test URLs

https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md?rgh-link-date=2022-10-07T05%3A16%3A38Z

## Before / After

Screen Shot 10
Screen Shot 12

### CODE REVIEW

File: source/features/useful-forks.tsx [hunk 1]
```diff
@@ -33,12 +35,14 @@ async function init(): Promise<void | false> {
 function createBannerLink(): JSX.Element {
 	// It must return an element for `attachElement`. It includes a space
 	return (
-		<span> You can find <a href={getUrl()} target="_blank" rel="noreferrer">useful-forks.github.io</a></span>
+		<span> You can use <a href={getUrl()} target="_blank" rel="noreferrer">useful-forks.github.io</a></span>
```
Comment (fregante) [inline source/features/useful-forks.tsx:38]: Also rewords it
