### PR TITLE
Restore `download-folder-button` on new file list UI

### LINKED ISSUE #6414: `download-folder-button` duplicated
### Steps to reproduce:

1. Open folder
2. Open file
3. Open folder again

ezgif-1-c1e5a66abb

The bug happens after clearing extension cache. 

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/tree/main/source/features

### Extension version

23.3.2

### Browser(s) used

Firefox 110

### PR DESCRIPTION
**Pull request by fregante**
- Closes #6414 
- Related to https://github.com/refined-github/refined-github/issues/6554

## Pros

- This also points the link to the correct folder, before it would get stuck
- This moves the link back into the dropdown, as the [feature screenshot](https://user-images.githubusercontent.com/46634000/158347358-49234bb8-b9e6-41be-92ed-c0c0233cbad2.png) showed

## Cons

- I'm pretty sure that archived repos don't have a "Delete directory" link so it's now broken there

## Test URLs

https://github.com/refined-github/refined-github/tree/main/source

## Screenshot

Screenshot 10

### CODE REVIEW

File: source/features/download-folder-button.tsx [hunk 1]
```diff
@@ -22,11 +22,22 @@ function add(folderDropdown: HTMLElement): void {
 	);
 }
 
+function add({parentElement: deleteDirectoryItem}: HTMLAnchorElement): void {
+	const item = deleteDirectoryItem!.cloneNode(true);
+	const link = item.firstElementChild as HTMLAnchorElement;
+	const downloadUrl = new URL('https://download-directory.github.io/');
+	downloadUrl.searchParams.set('url', location.href);
+	link.href = downloadUrl.href;
+	link.textContent = 'Download folder';
```
Comment (fregante) [inline source/features/download-folder-button.tsx:31]: This also clears a redundant `span` which happens to also be what sets the text color to red on "Delete directory"


Screenshot 11

Comment (fregante) [reply source/features/download-folder-button.tsx:31]:
```suggestion
	link.textContent = 'Download directory';
```
