### PR TITLE
`view-last-pr-deployment` - Restore feature

### LINKED ISSUE #9249: `view-last-pr-deployment` broken on new PR view
See context in https://github.com/refined-github/refined-github/issues/8946

### Test URL

https://github.com/refined-github/sandbox/pull/1

### PR DESCRIPTION
**Pull request by fregante**
- Fixes https://github.com/refined-github/refined-github/issues/9249

## Test URLs

https://github.com/fregante/bundle/pull/2

## Screenshot

Screenshot 30

### CODE REVIEW

File: source/features/view-last-pr-deployment.tsx [hunk 1]
```diff
@@ -12,21 +12,24 @@ function addLink(header: HTMLElement): void {
...
 		<a
-			className="rgh-last-deployment btn btn-sm d-none d-md-block mr-1"
+			className="rgh-last-deployment btn d-none d-md-block mr-1"
 			target="_blank" // Matches GitHub’s own behavior
 			rel="noopener noreferrer"
 			href={lastDeployment.href}
 		>
 			<RocketIcon className="mr-1 v-align-text-top" />
-			Latest deployment
+			View deployment
```
Comment (fregante) [inline source/features/view-last-pr-deployment.tsx]: Changed to match GitHub's wording, I think it's implied that it's the "latest", just like the "PR status" refers to the latest commit

File: source/features/view-last-pr-deployment.tsx [hunk 2]
```diff
@@ -12,21 +12,24 @@ function addLink(header: HTMLElement): void {
...
 		</a>,
 	);
 }
 
 function init(signal: AbortSignal): void {
-	observe('.gh-header-actions', addLink, {signal});
+	observe([
+		'button[class*="PullRequestCodeButton"]',
```
Comment (fregante) [inline source/features/view-last-pr-deployment.tsx:31]: This might not be the right position in cases where the header has 2 buttons (PR status | Code)

Comment (fregante) [reply source/features/view-last-pr-deployment.tsx:31]: Fixed spacing and alignment in latest version:

Screenshot 22

File: source/features/view-last-pr-deployment.tsx (hunk 1 above)
Comment (fregante) [reply source/features/view-last-pr-deployment.tsx]: I wonder if it should just be "Deployment" since this takes space away from the PR title

Screenshot 23

Comment (SunsetTechuila) [reply source/features/view-last-pr-deployment.tsx]: I'd make it a tooltipped icon button

Comment (fregante) [reply source/features/view-last-pr-deployment.tsx]: Yeah that's not a bad idea. The rocket is uniquely used for deployments anyway

**Review by SunsetTechuila — APPROVED** [review]
